### ISSUE TITLE
How to deploy nsm in Host

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10232]
Hi, i have two questions

Question1:
I want to deploy nsm in Host, but i not found ,how to do it ?
Qusetion2:
If I can deploy nsm in host, How to let nsm deployed in k8s can connect nsm deployed in host?

Thanks

**Comment by denis-tingaikin** [comment]
Hello @316953425 , 

I feel you might be interested in this example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc
