### ISSUE TITLE
About example Kernel2Wireguard2Kernel

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10230]
Hi
I deploy a example :https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/use-cases/Kernel2Wireguard2Kernel

Only change patch-nse.yaml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CIDR_PREFIX
              **value: 172.16.1.1/24**
            - name: NSM_PAYLOAD
              value: IP
            - name: NSM_SERVICE_NAMES
              value: "kernel2wireguard2kernel"
            - name: NSM_REGISTER_SERVICE
              value: "false"

After done

I exec kubectl exec -it alpine -n default -- /bin/sh
I found nsc ip is 172.16.1.1/32

I exec kubectl exec -it nse-kernel -n default -- /bin/sh
I found nsc ip is 172.16.1.0/32

But 
I in nsc ping 172.16.1.2 is ok
I want to know, nsc and nse no have 172.16.1.2,172.16.1.2 is configed where?

**Comment by NikitaSkrynnik** [comment]
Hello. I checked your scenario on v1.11.0 and v1.6.1 and I can't ping 172.16.1.2 from NSC. Could you please tell more about your environment. Is there a chance you have 172.16.1.2 outside the NSM network which is reachable from NSC?

**Comment by 316953425** [comment]
> Hello. I checked your scenario on v1.11.0 and v1.6.1 and I can't ping 172.16.1.2 from NSC. Could you please tell more about your environment? Is there a chance you have 172.16.1.2 outside the NSM network which is reachable from NSC?

Hi NikitaSkrynnik，
Thanks for you reply , 172.16.1.2 is configed outside the NSM network, this is my environment problem，NSM is work well
But I hava anther question
Also use this example：https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/use-cases/Kernel2Wireguard2Kernel

If i modify deployments-k8s-release-v1.6.1/apps/nse-kernel/nse.yaml as followed：

          **image: ghcr.io/networkservicemesh/cmd-nse-icmp-responder:v1.6.1
          #image: nelson/ubuntu:16.04**
          imagePullPolicy: IfNotPresent

pod cannot start，Could you tell me why? Is it possible to  replace cmd-nse-icmp-responder image with my own route forwarding mirror ?

Thanks

**Comment by NikitaSkrynnik** [comment]
I think it's possible to use other images if they implement this [service](https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/networkservice.proto#L33).

cmd-nse-icmp-responder implements [server side](https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L202) of the service.

If you want to implement your own version of NSE you can use our [SDK](https://github.com/networkservicemesh/sdk) to do it.

**Comment by 316953425** [comment]
> I think it's possible to use other images if they implement this [service](https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/networkservice.proto#L33).
> 
> cmd-nse-icmp-responder implements [server side](https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L202) of the service.
> 
> If you want to implement your own version of NSE you can use our [SDK](https://github.com/networkservicemesh/sdk) to do it.

Hi NikitaSkrynnik
Thanks for you reply
Could you give me a simple example , how to implement my NSE use sdk?

Thanks

**Comment by NikitaSkrynnik** [comment]
There is no documentation for how to implement your own NSEs yet. You can check [cmd-nse-icmp-responder](https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go). It's one of the simpliest implementations

**Comment by 316953425** [comment]
I also use https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/use-cases/Kernel2Wireguard2Kernel
When i change patch-nse.yaml 
add ipv6 cdir 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CIDR_PREFIX
              value: 10.199.1.1/16
            - name: NSM_PAYLOAD
              value: IP
            - name: NSM_SERVICE_NAMES
              value: "kernel2wireguard2kernel"
            - name: NSM_REGISTER_SERVICE
              value: "false"
            **- name: NSM_IPV6_PREFIX
              value: fd00:1111:2001:1234::/112**

when nsc-pod and nse-pod start
I Found ipv6 address not configed on nic 

nsc ip is :
5: nsm-1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1440 qdisc mq state UNKNOWN group default qlen 500
    link/none
    inet 10.199.0.1/32 scope global nsm-31xx
       valid_lft forever preferred_lft forever
    inet6 fe80::dbac:e5c0:88c7:3982/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

Could you tell me how to use ipv6 in nsm-1 interface ?

Thanks

**Comment by NikitaSkrynnik** [comment]
@316953425 you can check this [example](https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/features/dual-stack/Kernel2Wireguard2Kernel_dual_stack) for IPv6 examples

**Comment by 316953425** [comment]
> @316953425 you can check this [examples](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/ipv6) for IPv6 scenarios

Hi, NikitaSkrynnik
Thanks for you reply
I want to know does you have a plan to write a doc tell new developer how to step by step make nse images?
thanks

**Comment by NikitaSkrynnik** [comment]
@316953425 Hi, we have plans to add documentation for custom NSE developement, but unfortunately we don't have resources for it now. If you have time for it, maybe you could help us with this by documenting what you learn about creating a custom NSE. We would really appreciate it. If you decide to do it, here is our repository for the documentation: https://github.com/networkservicemesh/site. Feel free to open a PR.

Could you please also create a new issue for this [problem](https://github.com/networkservicemesh/deployments-k8s/issues/10230#issuecomment-1803598010)?

Usually we use the principle `one problem - one issue`, this way we will better understand how many problems (and questions) we really have.
You can also join our [nsm-dev](https://cloud-native.slack.com/messages/CHSKJ4849/) channel in Slack and ask questions there to get answers faster and discuss problems in one thread without creating issues. You can also find more useful links here: https://networkservicemesh.io/community

**Comment by 316953425** [comment]
> @316953425 Hi, we have plans to add documentation for custom NSE developement, but unfortunately we don't have resources for it now. If you have time for it, maybe you could help us with this by documenting what you learn about creating a custom NSE. We would really appreciate it. If you decide to do it, here is our repository for the documentation: https://github.com/networkservicemesh/site. Feel free to open a PR.
> 
> Could you please also create a new issue for this [problem](https://github.com/networkservicemesh/deployments-k8s/issues/10230#issuecomment-1803598010)?
> 
> Usually we use the principle `one problem - one issue`, this way we will better understand how many problems (and questions) we really have. You can also join our [nsm-dev](https://cloud-native.slack.com/messages/CHSKJ4849/) channel in Slack and ask questions there to get answers faster and discuss problems in one thread without creating issues. You can also find more useful links here: https://networkservicemesh.io/community

Hi , i want to do some NSE developement, but i can not found any documentation for it .
If you have some documentation for develop nse, could you tell me ?
