### ISSUE TITLE
External NSC fix interface problem

### ISSUE THREAD

**Issue by isZams** [networkservicemesh/deployments-k8s#10580]
## Description
Hi all, I was testing the example related to the configuration of an [external client](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc) to the cluster and noticed how the configuration of the MetalLB LoadBalancer needs to be changed.
In fact, in the [guide](https://kind.sigs.k8s.io/docs/user/loadbalancer/) offered by Kind, it is pointed out that the method through the ConfigMap is no longer supported.
One should run these commands

```
`kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml`
```

```

kubectl wait --namespace metallb-system \
                --for=condition=ready pod \
                --selector=app=metallb \
                --timeout=90s
```
```
` kubectl apply -f https://kind.sigs.k8s.io/examples/loadbalancer/metallb-config.yaml`
```
I tried to open a pull request  to make noticed this, but it failed. 
I followed the instructions inside the example, but apparently the external docker fails to communicate with the service: in fact the 2 kernel interfaces that should be available, are not created. 
I don't know if it affects the order but this is what I followed:
LoadBalancer , via the commands provided above and offered by the guide;
[`DNS,`](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc/dns);
[External Docker](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc/docker);
[Spire](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/spire/single_cluster);
[SPIFFE](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc/spiffe_federation) ;
I then ran the [command](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc) to configure the cluster with the NSM resources, and finally the deployment for the [example](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc/usecases/Kernel2IP2Kernel).

Do you have any hints for solving this problem?

**Comment by NikitaSkrynnik** [comment]
Hello @isZams. I tried the new commands and External NSC worked well. The only thing I've changed is `address pool` for metal LB. Could you please check [this section](https://kind.sigs.k8s.io/docs/user/loadbalancer/#setup-address-pool-used-by-loadbalancers)? The `address pool` should be within `kind` docker network

**Comment by isZams** [comment]
@glazychev-art Sorry for the late reply. I tried with this new configuration and now it works. Thanks a lot for your time and work.
By the way i opened 3 PR in the site's repository to add more information that may useful for having a better idea of some aspects of NSM.
Thanks again

**Comment by denis-tingaikin** [comment]
@isZams Many thanks, we'll review these PRs soon.

Seems like the ticket resolved. Feel free to reopen if we missed something!
