### ISSUE TITLE
Packet drop in forwarder-vpp

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/deployments-k8s#10644]
## Failure Information

Continuation of issue #10154
Packets missing in NSE container. Pcap trace collected on node and inside the container. The packet arrived to the node but missing from NSM interface. There is no error or any failure notice in the logs.
Now the issue was reproduced with low packet rate, UDP traffic and vpp trace enabled. The packet trace does not contains the packet so it wasn't processed by vpp.
It is a Kernel2Ethernet2Kernel like setup. One NSE instance and one NSC instance are deployed to different nodes.

## Context

* NSM Version: 1.11.1.

## Failure Logs

- The receiver.pcap contains the dump collected in NSE container
- The node16.pcap contains the tcpdump collected on NSE node, on interface running the VXLAN traffic (TUNNEL_IP)
- The vpp_trace-forwarder-vpp-p757h contains the vpp packet trace collected on forwarder from this node.

The packet with frame number 53676 from node16.pcap can not be seen on receiver.pcap. The previous and next packet:

```
frame no.
receiver.pcap                  node16.pcap
8271                                53669 
8273                                53687
```

These packets can be identified in vpp packet trace based on the ip-checksum and timestamps. (slice of packet trace which should contain the missing packet in trace-slice.txt)

[node16.pcap.zip](https://github.com/networkservicemesh/deployments-k8s/files/13490039/node16.pcap.zip)
[receiver.pcap.zip](https://github.com/networkservicemesh/deployments-k8s/files/13490183/receiver.pcap.zip)
[vpp_trace-forwarder-vpp-p757h.zip](https://github.com/networkservicemesh/deployments-k8s/files/13490222/vpp_trace-forwarder-vpp-p757h.zip)

[trace-slice.txt](https://github.com/networkservicemesh/deployments-k8s/files/13490192/trace-slice.txt)

**Comment by glazychev-art** [comment]
Thanks @ljkiraly, 
Do you have any script that allows you to find a dropped frame? How did you find 53676?

**Comment by ljkiraly** [comment]
@glazychev-art It was printed out by  the traffic generator tool. Unfortunately it is not open-sourced and I have no access to this tool. By the way such a script would be useful.

**Comment by glazychev-art** [comment]
@ljkiraly 
Got it, thanks.
Is it possible to collect frames but use ping (ICMP) rather than UDP traffic? Without any analysis, I will do it myself, just pcap file from NSE node.
Something like:
`ping 169.254.0.1 -i 0.01 -s 1100`
(or any other interval and size)

**Comment by glazychev-art** [comment]
@ljkiraly 
Could you please check this forwarder-vpp image?
`artgl/cmd-forwarder-vpp:af_v2_4096`

**Comment by ljkiraly** [comment]
Hi @glazychev-art, I will update the traces collected during ICMP (ping) traffic as soon as we manage to do the testing.

> Could you please check this forwarder-vpp image?

Yes, it will take some time to deploy it.

**Comment by szvincze** [comment]
> `artgl/cmd-forwarder-vpp:af_v2_4096`

Hi @glazychev-art, can you please give a short description what has been changed in this image?

**Comment by ljkiraly** [comment]
@glazychev-art The pcap files collected during ICMP traffic
[pingonly.zip](https://github.com/networkservicemesh/deployments-k8s/files/13526201/pingonly.zip)
Until now we do not see drops with the artgl/cmd-forwarder-vpp:af_v2_4096 image

**Comment by glazychev-art** [comment]
Good!

Thanks for the traces, but in fact we are more interested in the dump received from the **_NSE node_** (like node16.pcap.zip attached above), because only on this basis we can understand whether the packet was lost by VPP or not

But in general, if `cmd-forwarder-vpp:af_v2_4096` will work fine for you, then dumps/traces are not necessary, since the reason is clear, I think.

**Comment by glazychev-art** [comment]
Thanks @ljkiraly !
I would also suggest to use af_packet v3. For now, regardless of performance, because there are questions about it. You just need to remove af packet v2 flag, framesPerBlocks and frameSize at all (use default values)

**Comment by szvincze** [comment]
> I would also suggest to use af_packet v3. For now, regardless of performance, because there are questions about it. You just need to remove af packet v2 flag, framesPerBlocks and frameSize at all (use default values)

We have already planned to try AF_PACKET v3, however we have seen significant increase of latency compared to v2. Have you managed to test it?
Anyway, we will verify it from packet dropping point of view and come back with the results.

**Comment by glazychev-art** [comment]
Yes, I tested it, and on different clusters it now shows different results. On the kind cluster, despite the fact that the ping latency has actually increased, iperf shows better results.
That's why I ask you to ignore performance for now. At the same time, I was unable to reproduce the current packet drops problem.

**Comment by glazychev-art** [comment]
Thanks @szvincze,
Did you notice these are the same drops that are indicated in the description? That is, frames that arrived at the host but were not processed by VPP.
Are there any drops on NSC/NSE? Like here for example: https://github.com/networkservicemesh/deployments-k8s/issues/10154#issuecomment-1810028393

**Comment by ljkiraly** [comment]
Hi @glazychev-art 

> Did you notice these are the same drops that are indicated in the description?


With the latest forwarder image (mentioned by @szvincze ) NO packet drops / re-transmissions can be seen with low packet rate. In actual tests the traffic is around 4000 pps rate.  It is almost impossible to collect traces everywhere at this high load. So it is harder to identify where the packets are dropped. The NSM interface statistics in NSC & NSE does not show dropped packets (as in https://github.com/networkservicemesh/deployments-k8s/issues/10154#issuecomment-1810028393 )

**Comment by edwarnicke** [comment]
Have you looked at the output of

```show run```

on VPP?  Among other things it will show you the average vector size... and that vector size gives you a sense of how overwhelmed (or not) vpp is.

**Comment by glazychev-art** [comment]
**Current state:**
1. Prepared a simple parser of pcap files for tests. For example, you can specify the path to the node16.pcap file (attached in the description) and all anomalies will be shown.
https://github.com/glazychev-art/pcapParser
2. Increased performance was achieved by setting different limits for pods:
 - [NSC (is set by webhook)](https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/admission-webhook-k8s/admission-webhook.yaml#L55) - cpu: 600m
 - [NSE](https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/nse-kernel/nse.yaml#L48) - cpu: 600m
 - [Forwarder-VPP](https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/forwarder-vpp/forwarder.yaml#L60) - cpu: 900m
3. Performance measurement depends on utilities. I use:
 - **_ping_**: `ping <dst-ip> -i 0,00005 -s 1400`
 - **_iperf_** (not iperf3).
 server: `iperf -s -u -i 1`
 client: `iperf -c <dst-ip> -i 1 -u -b 10000pps`
 - **_echoping_** (https://github.com/wxiaoguang/echoping)
 server: `echoping -listen <dst-ip>:1111`
 client: `echoping -connect udp://<dst-ip>:1111/ -ping-interval 0.05ms`
 installation:
```
 apk add gcompat
 wget https://github.com/wxiaoguang/echoping/releases/download/v0.3.0/echoping_0.3.0_linux_amd64.tar.gz
 tar -zxvf echoping_0.3.0_linux_amd64.tar.gz -C /bin
```

**Comment by glazychev-art** [comment]
Prepared the fix for VPP:
https://gerrit.fd.io/r/c/vpp/+/40119

**Comment by glazychev-art** [comment]
Looks like done. Feel free to reopen, if you see any problem
