### ISSUE TITLE
about policy-based-routing how to

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10774]
hi @glazychev-art 
I deployed https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/policy-based-routing. It seems that there is no problem with the deployment. What is the use of policy routing? Can you introduce me to a usage scenario?
Thanks

**Comment by glazychev-art** [comment]
I think you need to study what this term means in computer networking. 
In short, it allows you to forward a packet not based on dst_ip (like normal routing), but based on other rules (src_ip, dport/sport and so on)

**Comment by 316953425** [comment]
> I think you need to study what this term means in computer networking. In short, it allows you to forward a packet not based on dst_ip (like normal routing), but based on other rules (src_ip, dport/sport and so on)

hi @glazychev-art 
Maybe there is something wrong with my expression
I know very well what policy routing does.

in Policy Based Routing 
NSC ip：172.16.1.101
NSE ip：172.16.1.100
I want to know under what circumstances do I need to configure policy routing for nsc? The nsm interfaces are all point-to-point.
thanks

**Comment by glazychev-art** [comment]
Q1:
The basic idea is that your endpoint can be configured in a certain way. Perhaps it can handle any traffic. For example, if you set:
```
    - proto: 17
      dstport: 6666
```
and call `nc -u 172.16.4.1 6666` from the client (NSC), your packet will be sent to the endpoint (NSE) despite of 172.16.4.1 address. Remember that NSC/NSE are mainly used as a sidecar to a user application (pod). And the user application can do anything.

Q2:
Agree. But it is just an example to show functionality. Perhaps you have a script on the NSE side that generates a file with PBR rules in the way that you need.
