### ISSUE TITLE
Add more aggressive forwarders restart test

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#10918]
## Overview

We already have healing tests that cover forwarder restarts:
https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/heal/local-forwarder-remote-forwarder
https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/heal/local-forwarder-death

We need to add a new one that will also cover:
- if there is no datapath healing. Currently, datapath healing helps us out in many cases. We need to make sure that healing based on monitor events also works well.
- forwarder death during a refresh.

**Comment by denis-tingaikin** [comment]
@glazychev-art Do you have an idea how can we wait for a client's refresh on CI?

**Comment by denis-tingaikin** [comment]
Seems like done
