### ISSUE TITLE
Impossible to start basic deployment on MacOS/Arm64

### ISSUE THREAD

**Issue by bellycat77** [networkservicemesh/deployments-k8s#10985]
## Expected Behavior

Run [basic](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic) deployment on MacOS

## Current Behavior

`forwarder-vpp` pod fails down

## Failure Information (for bugs)

```
% kubectl logs forwarder-vpp-svnlv -n nsm-system
Jan 11 11:20:12.970 [ERRO] [cmd:/bin/forwarder] <nil>
Jan 11 11:20:12.971 [FATA] error getting x509 source: context canceled
```

## Steps to Reproduce

```
kind create cluster
kubectl apply -k "https://github.com/networkservicemesh/deployments-k8s/examples/spire/single_cluster?ref=v1.12.0-rc.1"
kubectl wait -n spire --timeout=1m --for=condition=ready pod -l app=spire-server
kubectl wait -n spire --timeout=1m --for=condition=ready pod -l app=spire-agent

kubectl apply -f https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/v1.12.0-rc.1/examples/spire/single_cluster/clusterspiffeid-template.yaml
kubectl apply -k "https://github.com/networkservicemesh/deployments-k8s/examples/basic?ref=v1.12.0-rc.1"
```

## Context

Host OS: MacOS Sonoma 14.2.1
CPU: M1
Docker version: 4.26.1
Kind version: kind v0.20.0 go1.20.5 darwin/arm64
Kind node version(s): v1.27.3 and v1.29.0
NSM versions: 1.10.0, 1.11.0, 1.11.1, 1.11.2, 1.12.0-rc.1

## Failure Logs

Logs file from ``kubectl cluster-info dump``:
[dump.txt](https://github.com/networkservicemesh/deployments-k8s/files/13902463/dump.txt)

**Comment by nephilimboy** [comment]
Hi,
Have you tried to change the build architecture of the nsmgr, forwarder-vpp, registry-k8s, admission-webhook-k8s (mentioned in the basic example kustomization.yaml file) from amd64 to arm64?

**Comment by bellycat77** [comment]
Have you tried to change the build architecture of the nsmgr, forwarder-vpp, registry-k8s, admission-webhook-k8s (mentioned in the basic example kustomization.yaml file) from amd64 to arm64?
No, I've tried just existing images only. Docker supports amd64 binaries on MacOS. It uses Rosetta emulator.

**Comment by denis-tingaikin** [comment]
I've tested both the Kind and the Docker K8s engine + M1 arm machine on MacOS 13 and MacOS 14. Everything is working perfectly.

I found that you've missed applying this:
```bash
kubectl apply -f https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/v1.12.0-rc.1/examples/spire/base/clusterspiffeid-webhook-template.yaml
```
That might be a root cause. 

Another potential point could be related to the Docker version. I've used `4.24.0`.

**Comment by bellycat77** [comment]
Yes, you are right. I've missed
```
kubectl apply -f https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/v1.12.0-rc.1/examples/spire/base/clusterspiffeid-webhook-template.yaml
```
But it didn't solve the problem.
Downgrading Docker Desktop to version 4.24.0 solves the problem

**Comment by denis-tingaikin** [comment]
We've added testing on arm64 https://github.com/networkservicemesh/integration-k8s-packet/actions/runs/8524562356/job/23349434961

Next time, we will be able to catch issues with arm64 via CI.

Thanks.
