### ISSUE TITLE
Question about change-nse-dinamically example 

### ISSUE THREAD

**Issue by isZams** [networkservicemesh/deployments-k8s#11114]
Hi everyone, I was wondering if it was possible to deploy pods only when they are actually requested. Let me explain: in the kustomization.yaml file, both "blue" and "green" endpoints are defined, which is why they are deployed even when the requested service is one of them. Wouldn't it be possible to send them running only when the service changes?

In this regard, could the "scale-from-zero" example be useful in some way?

**Comment by isZams** [comment]
Thanks for your reply @glazychev-art.
Is there any reason why it was decided in "change-nse-dinamically" to deploy both endpoints at the beginning or not?

**Comment by glazychev-art** [comment]
I guess there are no special reasons. The main idea of ​​this example is that if the nerwork service parameters change, the correct NSE will be selected

**Comment by isZams** [comment]
@glazychev-art Ok thanks.
I was able to get it working. I have more questions: regarding the supplier, can you change the template while the pod is in the running state? maybe by doing a restart?  (Since config maps are used I think it is not possible to do this while it is in the running state but I ask to be sure).

Or do I have to have a supplier for each different template that i want to supply?

**Comment by isZams** [comment]
@glazychev-art Hello and sorry again for bothering.

I was testing the example with the external nsc together with change-nse-dynamically and "scale-from-zero".
Basically I wanted to see what happens in case you go to change the endpoints associated with the service requested by the external client.
When I deploy the first network service I get the kernel interfaces, both on the external nsc and the correct nse, with the correct IP addresses.

After that, when I change endpoints, and I go to use the second endpoint, the same interface is created within it that I had in the previous case, so with the same IP address, when in fact it should change.

Here you can find the files that i'm using
[change-nse-dynamically.zip](https://github.com/networkservicemesh/deployments-k8s/files/14009619/change-nse-dynamically.zip)
[external_nsc.zip](https://github.com/networkservicemesh/deployments-k8s/files/14009620/external_nsc.zip)

**Comment by glazychev-art** [comment]
> regarding the supplier, can you change the template while the pod is in the running state

I looked at the supplier code, and currently on-the-fly changes are not supported. The updated config map will be used only after the supplier pod restart.

> Or do I have to have a supplier for each different template that i want to supply?

Depends on your goals. In short: one template - one supplier.

> Here you can find the files that i'm using

I looked at the files. I don't quite understand what you want to achieve..
First of all, in case of both endpoints you will have the same addresses, because you have the same CIDR for blue-nse.yaml and pod-template.yaml
I would also recommend removing the
`nodeName: {{index .Labels "nodeName"}}`
from the template. Because scale-from-zero example says, that "The requested endpoint will be automatically spawned on the same node as NSC". This happens because of this line. But this is not possible because your external client is not in Kubernetes.

**Comment by isZams** [comment]
Thank you very much for your reply @glazychev-art . I hadn't noticed that error.
Anyway, the basic idea was to have an external client that would connect to network services within Kubernetes. I wanted to test this scenario in case the network service definition varied at runtime(like in the "change-nse-dynamically" example).

**Comment by glazychev-art** [comment]
Okay, got it. You are on the right track!
Ping me if something goes wrong

**Comment by glazychev-art** [comment]
Feel free to reopen the issue if you see any problem
