### ISSUE TITLE
Multiple services request within ext_client scenario

### ISSUE THREAD

**Issue by isZams** [networkservicemesh/deployments-k8s#11352]
## Question

Hello, everyone.
I was trying to implement the example where the [client outside the cluster](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/k8s_monolith/external_nsc), as in this example, goes to request two different services within the cluster.
I am currently using the example within the zip file, and what I get is only the first interface bound to one of the 2 services. The rest of the configuration is the same as in the example in the repository.
The pods within the cluster are both in a running state.
I don't know if the problem could be related to the dns and if so, I would like to ask you the kindness of explaining how I can go about working with this specific part.

[Kernel2IP2Kernel.zip](https://github.com/networkservicemesh/deployments-k8s/files/14483983/Kernel2IP2Kernel.zip)

**Comment by VitalyGushin** [comment]
@isZams You may deploy a single nse and specify 2 services in the env variable:

```
            - name: NSM_SERVICE_NAMES
              value: "kernel2ip2kernel-monolith-nsc,kernel2ip2kernel-monolith-nsc-2"
```

**Comment by VitalyGushin** [comment]
Got it. In your example, the second endpoint is not on the same subnet as the first one. Will try to figure out how to fix this.
