### ISSUE TITLE
Request for information about Roles and ClusterRoles

### ISSUE THREAD

**Issue by rpiceage** [networkservicemesh/deployments-k8s#1191]
Could you add some example Roles and ClusterRoles?
I need to define Roles/ClusterRoles for the cmd-registry-memory, cmd-nsmgr and cmd-forwarder-vpp and have no info about exactly what resources and verbs are needed for each of them. An example yaml would be very welcome.

**Comment by denis-tingaikin** [comment]
Could you explain for what do you need roles?

**Comment by rpiceage** [comment]
We are working on a Helm chart for NSM, and have to meet some requirements. One of them is that DaemonSets, Deployments, etc should not use the default roles, but should have their own, together with RoleBinding.

**Comment by edwarnicke** [comment]
@rpiceage OK... so lets talk through this to make sure I understand :)

Are you asking the that Role and ClusterRole for the various Pods/Daemonsets/Deployments in the NSM system?

If so, I presume you are seeking to converge on the most restrictive Role/ClusterRole that will work for those Pods/Daemonsets/Deployments correct?

I believe that the only cmd-* we have that are interacting with the k8s API are:

- cmd-forwarder-sriov
- cmd-exclude-prefixes-k8s
- cmd-registry-k8s

**Comment by rpiceage** [comment]
@edwarnicke Yes, you got it right about the most restrictive Role.
Does this mean that cmd-registry-memory, cmd-nsmgr and cmd-forwarder-vpp do not require anything specified it their most restricted Roles?

**Comment by edwarnicke** [comment]
@rpiceage Not in terms of their interactions with the K8s API.  cmd-forwarder-vpp *does* need to run privileged.

**Comment by rpiceage** [comment]
@edwarnicke Thanks for the info.

**Comment by edwarnicke** [comment]
@rpiceage Which brings us around to the question... do you need Roles and ClusterRoles for:

* cmd-forwarder-sriov
* cmd-exclude-prefixes-k8s
* cmd-registry-k8s

I believe cmd-forwarder-sriov has dependencies on k8s due to it providing a device plugin

I believe cmd-exclude-prefixes-k8s mostly reads from the K8s API, but also writes ConfigMaps

cmd-registry-k8s maintains CRDs to store NSM registry entries.
