### ISSUE TITLE
Bug with re-deployment of nse-composition with kernel-interfaces

### ISSUE THREAD

**Issue by isZams** [networkservicemesh/deployments-k8s#11927]
## Expected Behavior
I would like to change the endpoint composition by adding a new pod in the middle of the chain, by simply modifying the network service definition file. 
## Actual Behavior

Actually if i add a new pod, there are some problems with the kernel interfaces. Assuming that initially i have this configuration:
```nsc --> passthrough-4 --> gateway```.
Then i want to move to this configuration:
```nsc--> test --> passthrough-4 --> gateway```.

The problem with the interfaces is between ```test and passthrough-4``` and then also within ```passthrough-4```.
Do you have any idea about the possible reasons?
I thought to have a similar  behaviour  when a client connects to a different service and therefore a new interface is established, as in the example of  ```change-nse-dynamically```.

Here there is the zip folder containing all the files that i'm using for this use case.
[kernel-composition.zip](https://github.com/networkservicemesh/deployments-k8s/files/15249944/kernel-composition.zip)

**Comment by denis-tingaikin** [comment]
If it's reproducing rarely, it's still a problem. So, does it reproducing?

**Comment by denis-tingaikin** [comment]
We want to reach a great quality, so feel free to report any suspected things and many thanks for testing !

**Comment by isZams** [comment]
Ok, as soon as i get some new information i will inform you. Anyway there are other stuff where i need your help, can you check the other issues?

**Comment by denis-tingaikin** [comment]
We saw other issues; currently, it requires prioritization from Ed and folks. You may raise these questions on our community calls(next tuesday). See the schedule and links here: https://networkservicemesh.io/community.

**Comment by isZams** [comment]
Ok. thanks for your reply and your time

**Comment by isZams** [comment]
After 1 hour i still have the previous problem. I found an error in the configuration file of "test" where i left the old value for the source selector within the cmd-nsc image and i thought that would be the solution but i was wrong.
