### ISSUE TITLE
Fix CRITICAL level issues from CVE scanner

### ISSUE THREAD

**Issue by Ex4amp1e** [networkservicemesh/deployments-k8s#12260]
https://github.com/networkservicemesh/deployments-k8s/security

- [x] Update go to v1.23 locally (code)
- [x] Update go to v1.23 locally (base image)
- [x] Update go to v1.23 (sdk) - minimal changes version https://github.com/networkservicemesh/sdk/pull/1664 (.github update required, Example: https://github.com/Ex4amp1e/.github/pull/1/commits/255dc4670535263c28acf41105a0f526e1eff97e)
- [x] Provide remaining - 2 weeks
- [x] Update go to v1.23 (code)
- [x] Update go to v1.23 (base image) - https://github.com/networkservicemesh/deployments-k8s/issues/12283
- [x] Update base to latest version ubuntu/alpine and etc. - https://github.com/networkservicemesh/deployments-k8s/issues/12283

**Comment by denis-tingaikin** [comment]
We decided to split work related to update linter on two parts:

1. Update linter config to v1.23 with minimal changes
2. Provide a list of linters that can be enabled in future.
