### ISSUE TITLE
Highload testing  v1.14.0-rc.3,  v1.14.0-rc.4,   v1.14.0-rc.5

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#12279]
We need to capture these metrics from rc.

- goroutines
- memory profiles
- mem usage
- fd count
- network interface count

before/after

**Comment by NikitaSkrynnik** [comment]
After 5h of testing of `rc.4`:
|            | nsmgr-r2pkr | nsmgr-6qlrv | forwarder-vpp-b7cs6 | forwarder-vpp-sx27j |
|------------|-------------|-------------|---------------------|---------------------|
| goroutines | 41          | 41          | 48                  | 48                  |
| fd count   | 20          | 20          | 47                  | 48                  |
| interfaces |             |             | 0                   | 2                   |

[profiles.zip](https://github.com/user-attachments/files/16992423/profiles.zip)

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik  Looks very clear. Could you also attach statistics before/after.

**Comment by denis-tingaikin** [comment]
Also, I think would be interesting to run tests on the public cluster with extreme light nsmgr setup, where: 
1. Logs should be used with INFO level
2. exclude prefix service should be removed.
3. health probes should be disabled from the deployment and docker image
4.  dlv should be removed from the docker image.

**Comment by NikitaSkrynnik** [comment]
Results of `rc.6` testing (about 600 scaling iterations):
|               | nsmgr-r2pkr | nsmgr-6qlrv | forwarder-vpp-b7cs6 | forwarder-vpp-sx27j |
|---------------|-------------|-------------|---------------------|---------------------|
| goroutines    | 41          | 41          | 48                  | 48                  |
| fd count      | 20          | 20          | 48                  | 48                  |
| interfaces    |             |             | 56                   |  32                  |
| memory before | 60          |    60      | 270                 | 270                 |
| memory after  |      61    |       76   | 403                | 419                |

**Comment by denis-tingaikin** [comment]
Seems like done. Thanks!
