### ISSUE TITLE
Update go to v1.23

### ISSUE THREAD

**Issue by Ex4amp1e** [networkservicemesh/deployments-k8s#12294]
Based on https://github.com/networkservicemesh/deployments-k8s/issues/12260

First step was to update base images to fix CVEs - https://github.com/networkservicemesh/deployments-k8s/issues/12283
Second (current) - to update source code go version

- [x] 1. .github
- [x] 2. cmd-template
- [x] 3. deployments-k8s
- [x] 4. sdk
- [x] 5. sdk-kernel
- [x] 6. sdk-k8s
- [x] 7. sdk-sriov
- [x] 8. sdk-ovs
- [x] 9. sdk-vpp
- [x] 10. api
- [x] 11. cmd-nsc
- [x] 12. cmd-forwarder-vpp
- [x] 13. cmd-forwarder-ovs
- [x] 14. cmd-forwarder-sriov
- [x] 15. cmd-nse-icmp-responder-vpp
- [x] 16. cmd-nse-vlan-vpp
- [x] 17. cmd-nse-supplier-k8s
- [x] 18. cmd-nse-l7-proxy
- [x] 19. cmd-exclude-prefixes-k8s
- [x] 20. cmd-map-ip-k8s
- [x] 21. cmd-admission-webhook-k8s
- [x] 22. cmd-cluster-info-k8s
- [x] 23. cmd-ipam-vl3
- [x] 24. cmd-nsc-init
- [x] 25. cmd-nsmgr
- [x] 26. cmd-nsmgr-proxy
- [x] 27. cmd-nse-vfio
- [x] 28. cmd-registry-memory
- [x] 29. cmd-registry-proxy-dns
- [x] 30. cmd-nse-remote-vlan
- [x] 31. cmd-nse-firewall-vpp
- [x] 32. cmd-nse-vl3-vpp
- [x] 33. cmd-nsc-vpp
- [x] 34. cmd-nse-simple-vl3-docker
- [x] 35. cmd-nsc-simple-docker
- [x] 36. cmd-registry-k8s
- [x] 37. cmd-nse-icmp-responder
- [x] 38. gotestmd
- [x] 39. integration-tests
- [x] 40. integration-k8s-kind
- [x] 41. integration-k8s-gke
- [x] 42. integration-k8s-aks
- [x] 43. integration-k8s-packet
- [x] 44. integration-k8s-aws
- [x] 45. integration-interdomain-k8s

ETA for each PR: 10-30m depending on required linter fixes

**Comment by Ex4amp1e** [comment]
@szvincze Hello
We have updated go version to 1.23  in source code. Can we merge it and test in RC.2?

**Comment by denis-tingaikin** [comment]
It's done, thanks!
