### ISSUE TITLE
Include cmd-exclude-prefixes-k8s

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/deployments-k8s#1353]
1. Add https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s to the apps.
2. Deploy cmd-exclude-prefixes-k8s with all examples
3. Provide examples to show cmd-exclude-prefixes-k8s working correctly, and exclude prefixes being excluded from IP ranges

**Comment by Mixaster995** [comment]
close with https://github.com/networkservicemesh/deployments-k8s/pull/3377
