### ISSUE TITLE
TestKernel2Vxlan2Memif become unstable after last merges

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#1758]
Logs: 
Build1:
[logs1](https://github.com/networkservicemesh/deployments-k8s/files/6648634/artifacts.zip)
Build2:
[logs2](https://github.com/networkservicemesh/deployments-k8s/files/6648638/Containers.logs.6.zip)

## Potential problem:

By my investigation, I found that we got red ci in kind on these changes: https://github.com/networkservicemesh/deployments-k8s/compare/7b34262f...7b7cb58da

The problem might be related to 

1. https://github.com/networkservicemesh/sdk/commit/7b63239a9b3bb56b8ce8bc3ba8aa492f96b0de53
2. https://github.com/networkservicemesh/api/pull/100

**Comment by Bolodya1997** [comment]
Closed by networkservicemesh/cmd-nsc#218, networkservicemesh/cmd-nsc-vpp#163.

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Nice!
