### ISSUE TITLE
memif2vxlan2memif: errors in nsmgr, no response for nsc

### ISSUE THREAD

**Issue by richardstone** [networkservicemesh/deployments-k8s#1887]
Hi,

I'm trying to deploy the memif2vxlan2memif example but getting strange errors in the local nsmgr of the nsc. On one machine the connection is fine, on the other the NSC is not getting a response, but the error is there in both try. 

I post the logs from the NSC and the NSMGR in both cases (bad, working). Could you please take a look at them?
[bad-memif2vxlan2memif-nsc.txt](https://github.com/networkservicemesh/deployments-k8s/files/6677241/bad-memif2vxlan2memif-nsc.txt)
[bad-memif2vxlan2memif-nsmgr.txt](https://github.com/networkservicemesh/deployments-k8s/files/6677242/bad-memif2vxlan2memif-nsmgr.txt)
[working-memif2vxlan2memif-nsc.txt](https://github.com/networkservicemesh/deployments-k8s/files/6677243/working-memif2vxlan2memif-nsc.txt)
[working-memif2vxlan2memif-nsmgr.txt](https://github.com/networkservicemesh/deployments-k8s/files/6677244/working-memif2vxlan2memif-nsmgr.txt)

The difference between the machines is the k8s version:
Working machine:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
NOT working machine:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-28T05:33:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks!

**Comment by denis-tingaikin** [comment]
Hello @richardstone,

Could you also share versions of your images?

**Comment by richardstone** [comment]
I'm using latest from the repo.

**Comment by denis-tingaikin** [comment]
@richardstone NSM works with k8s v1.17.11 or higher.

**Comment by denis-tingaikin** [comment]
So closing this.

@richardstone Be free to reopen the issue if I missed someting!
