### ISSUE TITLE
Destructive Chaos Testing: Integration tests (multi death cases)

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/deployments-k8s#1928]
## Overview

Cover the following heal scenarios with integration tests:
1. Local NSMgr(r) +
   1. Local Endpoint(d)
   2. Remote NSMgr(d)
   3. Remote Forwarder(d)
   4. Remote Endpoint(d)
   5. Registry(r)
2. Remote NSMgr(d) +
   1. Remote Endpoint(d)
   2. Registry(d)

## Blockers
* extended sandbox testing - https://github.com/networkservicemesh/sdk/issues/899

**Comment by Bolodya1997** [comment]
@edwarnicke 
Do we want to skip some steps now and return to them later? Or probably there is something else I am missing?
Please share your thoughts.

**Comment by glazychev-art** [comment]
New multideath cases were added - https://github.com/networkservicemesh/deployments-k8s/tree/v1.12.0/examples/heal
