### ISSUE TITLE
NSM interface deleting periodically 

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#1929]
## Logs

```
stderr F Jun 17 10:50:48.232 [ERRO] [cmd:[/bin/app]] [healServer:processHeal] Failed to heal connection alpine-cl-0: Error returned from sdk/pkg/networkservice/common/authorize/authorizeClient.Request: rpc error: code = PermissionDenied desc = no sufficient privileges
```

## Steps to reproduce
1. Run webhook example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/webhook
2. don't cleanup
3. wait for 20-30 min

**Actual:**

[nsm-toggling.webm.zip](https://github.com/networkservicemesh/deployments-k8s/files/6687134/nsm-toggling.webm.zip)

**Expected:**
NSM interface should not be deleted if data plane and control plane are fine

**Comment by denis-tingaikin** [comment]
Cannot reproduce. It looks like the problem related to tokens lifetime.

**Comment by denis-tingaikin** [comment]
Tested on kind. The issue is reproducible.

**Comment by denis-tingaikin** [comment]
Logs from my local running:

[nsc-init.txt](https://github.com/networkservicemesh/deployments-k8s/files/6688056/nsc-init.txt)
[nsc.txt](https://github.com/networkservicemesh/deployments-k8s/files/6688057/nsc.txt)

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we consider this issue ASAP?

**Comment by edwarnicke** [comment]
@denis-tingaikin Yes

**Comment by denis-tingaikin** [comment]
**Root cause:**

1. Spire gives a certificate for 1h
2. NSM schedules refresh after 1h * 1/3
3. On refreshing spire updates certificates for all applications
4. At refresh moment nsmgr has a new certificate from spire, but authInfo from gRPC keeps old certificate from step1.

Currently, I'm not found a good solution for this issue, started to look into gRPC source code.

**Comment by denis-tingaikin** [comment]
Tested today two workarounds:
1. https://golang.org/pkg/crypto/tls/#RenegotiationSupport -- it is not helped
2. remove connection caching in connect -- it is working

Still looking for other solutions.

**Comment by denis-tingaikin** [comment]
@edwarnicke 

I've asked spire guys about the issue and got the next answer:

> Andrew Harding  14 hours ago
This is expected. gRPC will reuse the existing connection when you issue RPCs unless you redial. Since no new TLS handshake takes place, the new client credential is never communicated.
white_check_mark
eyes
raised_hands




>Andrew Harding  14 hours ago
The x509source returns a channel from Updated() that callers can use to know when the SVID has been updated so they can re-establish a connection with the new credential.

**Question:**

Can we modify `connect` chain elements to wait for update SVID(Note: we can just pass option to wait to channel to not depend on spire functions)?

**Comment by denis-tingaikin** [comment]
Currently we have the next options to fix the issue:

1. Do redial as suggested spire guys on svid updating https://github.com/networkservicemesh/deployments-k8s/issues/1929#issuecomment-870508779
2. Remove policy `last token signed`.
3. Keep and use first certificates for client and server on token generating.
4. Your option.

For me option 1 looks good.

@edwarnicke Please share your thoughts on these options.

**Comment by edwarnicke** [comment]
I'm curious... are they saying that GRPC won't close existing connections that have a TLS certificate that has expired after the connection was established?

**Comment by denis-tingaikin** [comment]
Yes, as I got it, a handshake is doing once per dial.

**Comment by edwarnicke** [comment]
@denis-tingaikin It looks like we need to do something that involves option 1 above... but lets try to keep it simple and natural :)

**Comment by denis-tingaikin** [comment]
The root cause is fixed in https://github.com/networkservicemesh/sdk/pull/1005

But I found that the issue can be reproduced via unstable healing. This reproducing periodically.
Tested  a fix https://github.com/networkservicemesh/sdk/pull/1005 without heal and it working fine in 100% cases.
