### ISSUE TITLE
Why is NS name appearing twice in yaml?

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/deployments-k8s#2008]
Why is the NS name appearing twice in the yaml

https://github.com/networkservicemesh/deployments-k8s/blob/838d4f09847d885c2f5cd497a0c67a1f7e93c056/examples/features/scale-from-zero/autoscale-netsvc.yaml#L5-L5

and

https://github.com/networkservicemesh/deployments-k8s/blob/838d4f09847d885c2f5cd497a0c67a1f7e93c056/examples/features/scale-from-zero/autoscale-netsvc.yaml#L9-L9

?

I would expect the NS name to be mapped into the metadata.name...

**Comment by denis-tingaikin** [comment]
Nice catch! I think we can fix it in https://github.com/networkservicemesh/sdk-k8s/blob/main/pkg/registry/etcd/nse_server.go#L130

**Comment by denis-tingaikin** [comment]
@edwarnicke Could you have look at https://github.com/networkservicemesh/sdk-k8s/pull/196?
