### ISSUE TITLE
Switch to using annotation for all kernel examples

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/deployments-k8s#2009]
Please switch all examples to use the annotations instead of just a bare NSC container with an ENV variable patches in.

**Comment by denis-tingaikin** [comment]
@edwarnicke It is possible for all kernel examples.
Could you say more about how we can change env to annotation for memif, vfio examples?

**Comment by edwarnicke** [comment]
kernel examples are sufficient :)

**Comment by denis-tingaikin** [comment]
OK, now it is clear, thanks!

**Comment by glazychev-art** [comment]
Improvement in logging required:
https://github.com/networkservicemesh/integration-tests/issues/694

**Comment by Mixaster995** [comment]
closed with https://github.com/networkservicemesh/deployments-k8s/pull/3663
