### ISSUE TITLE
Sometimes Close doesn't reach nsmgr

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#2085]
When running scalability tests (not yet uploaded) I found an issue with [heal working indefinitely](https://github.com/networkservicemesh/deployments-k8s/issues/2003).
When investigating it, I found that one of the reasons this was happening was that nsmgr never received `Close` for some of the connections.
Logs: [logs.zip](https://github.com/networkservicemesh/deployments-k8s/files/6787185/logs.zip)
There is a bunch of connections in these logs. You can use `grep 79b30cf1-1629-440c-8507-7e535d60295d` to get the part of the logs that allows you to see the issue.

**Comment by Bolodya1997** [comment]
This is caused by the lack of resources, doesn't look like we can do something here instead of suggesting users to increase CPU limits.

@denis-tingaikin 
Thoughts?

**Comment by Bolodya1997** [comment]
Filed a more detailed issue for this, provided few possible solutions there - https://github.com/networkservicemesh/sdk/issues/1031.
