### ISSUE TITLE
Rework nse-composition example to not use 'kustomize' directly

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/deployments-k8s#2123]
## Issue

Right now script for nse-composition example call `kustomize` directly instead of `kubectl apply -k`, because for some reason yet to be known kubectl command failed to work. Investigate this issue ASAP

**Comment by Mixaster995** [comment]
After some investigation, i think it's not gonna work. For some reason(i think it might be old version of kustomize in kubectl used on ci kind clusters) `kubectl apply -k` not working the same as `kustomize build`.

**Comment by edwarnicke** [comment]
@Mixaster995 Why not?  We really *do* from a usability point of view need to be able to use `kubectl apply -k` ... why is that having issues?

**Comment by Mixaster995** [comment]
@edwarnicke well, hard to tell the exact cause of issue - right now it working on my local machine kind, but not working on any ci kind setup and the only difference i found is slightly different kubectl version. I will rethink this again and make some changes in test files for it to work with `kubectl apply -k` correctly.
