### ISSUE TITLE
Wireguard feature tests are unstable

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#2161]
### Build
https://github.com/networkservicemesh/integration-k8s-aks/runs/3061957795?check_suite_focus=true

### Logs
[logs-157.zip](https://github.com/networkservicemesh/deployments-k8s/files/6813395/logs-157.zip)

Output: 
```
TestRunFeatureSuite1
...
  TestMemif2Wireguard2Kernel:1 | Test execution failed TestMemif2Wireguard2Kernel
  TestKernel2Wireguard2Kernel:1 | Test execution failed TestKernel2Wireguard2Kernel
```

**Comment by edwarnicke** [comment]
@artem-belov Have we seen this lately?

**Comment by glazychev-art** [comment]
If we look at the logs, the problem was related to: https://github.com/networkservicemesh/sdk/issues/1048

Close this issue
