### ISSUE TITLE
NSM have high CPU usage when errors happen

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#2368]
When running [scalability tests](https://github.com/networkservicemesh/deployments-k8s/issues/1015) I found out that when heal starts, NSM consume roughly 1 core for each of the connections to heal for several seconds.
CPU profiles, that can be found [here](https://github.com/networkservicemesh/deployments-k8s/issues/1015#issuecomment-886616495), suggest that the CPU load is caused by `log (*groupLogger) Errorf` → `debug Stack`.
The likely reason for this is the following line:
https://github.com/networkservicemesh/sdk/blob/92b282404ca12856deffaa8ddc91b6ba76cd8375/pkg/tools/log/spanlogger/spanlogger.go#L68
In this line we create a new stack snapshot each time we log anything as error, and when a chain element at the end of the chain returns an error, almost all of previous elements also return errors.

**Comment by d-uzlov** [comment]
I deleted `debug.Stack()` part from span logger and rerun the tests, and it seems to have fixed the CPU load.

**Comment by denis-tingaikin** [comment]
Seems like fixed by https://github.com/networkservicemesh/sdk/pull/1053
