### ISSUE TITLE
NSM Connection fails if spire-agent restarts on NSC node

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/deployments-k8s#2393]
## Expected Behavior
NSM connection shouldn't fail is spire-agent dies for some little time, or should be eventually restored if it dies for a long time.

## Current Behavior
NSM connection fails if spire-agent restart on NSC node:
1. Refresh Request from NSC to NSMgr fails (NSC -> NSE network connection still exists).
2. Healing from NSC to NSMgr fails (NSC -> NSE network connection fails).

## Steps to Reproduce

1. Run kernel2kernel test case, check that ping is working.
2. Restart `spire-agent` pod on the NSC node.
3. Wait for the token timeout.
4. Ping is not working.

## Failure Logs
[nsc-kernel-7cb47459d5-g9j6c.log](https://github.com/networkservicemesh/deployments-k8s/files/6915417/nsc-kernel-7cb47459d5-g9j6c.log)
[nsmgr-qq66h.log](https://github.com/networkservicemesh/deployments-k8s/files/6915419/nsmgr-qq66h.log)
[forwarder-vpp-hgttp.log](https://github.com/networkservicemesh/deployments-k8s/files/6915416/forwarder-vpp-hgttp.log)
[nse-kernel-79ffb869cc-796fc.log](https://github.com/networkservicemesh/deployments-k8s/files/6915418/nse-kernel-79ffb869cc-796fc.log)

**Comment by Bolodya1997** [comment]
Seems to be related to https://github.com/networkservicemesh/deployments-k8s/issues/1929.

**Comment by denis-tingaikin** [comment]
Don't quite follow how it is related to #1929. Could you say more?
