### ISSUE TITLE
TestRunFeatureSuite/TestDns test is unstable

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/deployments-k8s#2412]
## Logs
https://github.com/networkservicemesh/integration-k8s-kind/runs/3225731571?check_suite_focus=true

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Could you please provide your investigation result?

**Comment by Bolodya1997** [comment]
1. Container has such initial setup:
```
resolv.conf
---
search a.com b.com. c.d.com
nameserver 10.96.0.10
options ndots:5
```
2. After `cmd-nsc-init` started it has the following setup:
```
resolv.conf
---
search a.com b.com. c.d.com
nameserver 127.0.0.1
options ndots:5
```
```
Corefile
---
. {
    forward . 10.96.0.10
    log
    reload
}
my-coredns-service {
    forward 172.16.1.100
    log
}
```
3. After `cmd-nsc` started it has the following setup:
```
resolv.conf
---
search a.com b.com. c.d.com
nameserver 127.0.0.1
options ndots:5
```
```
Corefile
---
. {
    forward . 127.0.0.1
    log
    reload
}
my-coredns-service {
    forward 172.16.1.100
    log
}
```

Because of `ndots:5` set by default `ping my-coredns-service` results in following DNS queries:
1. my-coredns-service.a.com -> 127.0.0.1
2. my-coredns-service.b.com -> 127.0.0.1
3. my-coredns-service.c.d.com -> 127.0.0.1
4. my-coredns-service -> 172.16.1.100

In exactly this order. So (1-3) queries starts running in loop and overloading coredns - so it just fails to reply for 4 query in time needed for the ping.

**Comment by denis-tingaikin** [comment]
@Bolodya1997 

OK, got it.

Please note: we want to have on `cmd-nsc` started have this section for any queries:
```
. {
    forward . 10.96.0.10
    log
    reload
}
```
It is critical. 

Please let me know if I can continue with on this issue OR please apply fixes in https://github.com/networkservicemesh/sdk/pull/1054

**Comment by Bolodya1997** [comment]
> It is critical.

Why do we need it?

**Comment by denis-tingaikin** [comment]
@Bolodya1997 
Please see at Specification of https://github.com/networkservicemesh/networkservicemesh/blob/master/docs/spec/dns-integration.md#specification
