### ISSUE TITLE
Spire failure causes NSMgr/Forwarder liveness probe failures

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/deployments-k8s#2766]
## Expected Behavior
NSMgr, VPP Forwarder liveness probes should fail and restart the pod only if there is some problem with the NSMgr, VPP Forwarder application.

## Current Behavior
If spire server/agent freezes for some time or restarts for a long time, NSMgr, VPP Forwarder liveness probes fail and restart pods.

## Possible solution
We can start additional gRPC server on some `unix:///health.service.sock` in insecure mode and register only `grpc_health_v1` service on it. In such case there will be no need to use spire for checking pod liveness.

**Comment by denis-tingaikin** [comment]
Waiting for tests results
