### ISSUE TITLE
Cover all variants of connection between nsc, nse via cmd-forwarder-vpp

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#312]
Currently, we have examples for:
1. `kernel2kernel`
2. `memif2memif`
3. `kernel2vxlan2kernel`

https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic#includes

These variants currently is not covered by integration:

1. `kernel2memif`
2. `memif2kernel`
3. `kernel2vxlan2memif`
4. `memif2vxlan2kernel`
5. `memif2memif`

**Comment by edwarnicke** [comment]
Don't we also have:
memif2vxlan2memif
