### ISSUE TITLE
Please use metadata.Labels in nse-composition example

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#3437]
We should use there
https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/passthrough-1.yaml#L25 a ref to https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/passthrough-1.yaml#L13-L14

## Solution

1. Add to NSM_LABELS ref to  https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/passthrough-1.yaml#L13-L14 // See at ref example https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/passthrough-1.yaml#L29-L32
2. Replace app label to https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/passthrough-1.yaml#L15 "passthrough-1"

**Comment by denis-tingaikin** [comment]
## Defenition of done


Check all places where is using labels and make sure that every place is using labels from the metadata.

**Comment by Mixaster995** [comment]
Initial solution was not working, so reverted it. Use `downwardAPI` to fix it

**Comment by edwarnicke** [comment]
I'm a bit confused as to what we are doing here and why.  It looks like we are trying to pull from the Pod labels into the NSM_LABELS... but I don't understand why we are trying to do that.

@denis-tingaikin Could you explain?

**Comment by denis-tingaikin** [comment]
> Could you explain?

In my mind, it can look for users more simply than adding additional labels via env.

**Comment by denis-tingaikin** [comment]
@edwarnicke I'm fine if you're ok with the current separated labels list.

**Comment by denis-tingaikin** [comment]
We don't need this for now. Closing.
