### ISSUE TITLE
TestRemote_nsm_system_restart_memif_ip is not stable

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#4248]
### Description

Sometimes wireguard chain element doesn't receive `WIREGUARD_PEER_ESTABLISHED` event after `nsm-system` restart
https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/up/peerup/common.go#L83-L99

### Build
https://github.com/networkservicemesh/integration-k8s-kind/runs/4760113155?check_suite_focus=true

### Logs
See v1.20.7 - `TestRunHealSuiteSingle/TestRemote_nsm_system_restart_memif_ip` and `TestRunHealSuiteSingle/TestRemote_nsmgr_restart_ip` (there is a guess that it doesn't work due to the fall of the previous)

[heal_tests.zip](https://github.com/networkservicemesh/deployments-k8s/files/7845604/heal_tests.zip)

**Comment by glazychev-art** [comment]
Part of - https://github.com/networkservicemesh/sdk/issues/1196

**Comment by denis-tingaikin** [comment]
The last incident was 30 days ago.  I think this is potentially fixed. Let's keep eye on this issue.

**Comment by denis-tingaikin** [comment]
@glazychev-art I think we need to re-enable the test and check is it still reproducing.

Also could you check latest logs
https://github.com/networkservicemesh/integration-k8s-kind/runs/4760113155?check_suite_focus=true?

**Comment by denis-tingaikin** [comment]
Is not reproducing.
