### ISSUE TITLE
Do you plan to add dual stack support for cmd-nse-icmp-responder?

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/deployments-k8s#4623]
Hello,

We plan to do some dual stack testing. I know that is supported by API and I already added some support to cmd-remote-vlan-nse. As I see there are IPv6 only tests already.

Do you plan to add support for dual stack in cmd-nse-icmp-responder?

I would like to be in alignment in cmd-remote-vlan-nse with the cmd-nse-icmp-responder. Currently I am using two environment variable to set the CIDR: 'NSM_CIDR_PREFIX' and 'NSM_IPV6_PREFIX'

One option is to keep it as is or I can change the cmd-remote-vlan-nse to accept a pair of address range (IPv4 and/or IPv6) in NSM_CIDR_PREFIX and parse it.

--
Laszlo

**Comment by edwarnicke** [comment]
@ljkiraly Dual stack testing in integration would be most welcome.  Please do note that in the cmd-forwarder-vpp testing... all tests are dual stack :)  I suspect you are correct that you will need to add a bit to cmd-nse-icmp-responder to get dual stack working.  I'd suggest looking at: https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/69c5a02595841f45cfc7fd303097f53e4e4a386c/internal/tests/suite_kernel_test.go#L107-L108

It basically shows that you can simply configure *two* ipams, each with different prefixes and two IP addresses will be issued.

**Comment by denis-tingaikin** [comment]
@edwarnicke, @ljkiraly Should we create another nse repo to demonstrate dual stack example? I think the more examples of nses we have the better

**Comment by edwarnicke** [comment]
I'd suggest we simply make this NSE able to handle multiple prefixes (similar to how cmd-forwarder-vpp does it).  Would be fairly simple, and allow us to do dual stack pretty trivially, without hardcoding the IPv4 or Ipv6-ness of things.

**Comment by denis-tingaikin** [comment]
OK, as I can see we already have PR for this https://github.com/networkservicemesh/cmd-nse-icmp-responder/pull/407 :+1:
