### ISSUE TITLE
Automerge job ca stuck and do not merge green PRs from NSMBot

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#475]
## Problem
Actual:
![image](https://user-images.githubusercontent.com/49399980/110179759-360e2900-7e3b-11eb-8f53-d579e2b9fdba.png)
Expected: All green PRs from NSMBot should be merged.

We need to investigate and fix this.

**Comment by denis-tingaikin** [comment]
Found error in logs of auto-merge job: `Pull request is not in a mergeable state: UNKNOWN.`

**Comment by denis-tingaikin** [comment]
@edwarnicke I see here these options at this moment:

1. Use another action: https://github.com/pascalgn/automerge-action.
2. Try to patch ridedott/merge-me-action (looks like it should retry do merge after some period for PRs in UNKNOWN state).
3. Do ridedott/merge-me-action twice.
4. Your option.

For me option 1 looks good, but Im not sure at 100% that it solves the issue.

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm not in any way attached to our current auto-merge action... so if another one looks better or more stable, I'm in favor of changing :)
