### ISSUE TITLE
Request for example of running multiple simultaneous forwarders

### ISSUE THREAD

**Issue by johlj** [networkservicemesh/deployments-k8s#505]
Implement/document a test scenario for running and configuring at least two different types of forwarders simultaneously.

For instance the vpp forwarder alongside the sriov forwarder

**Comment by denis-tingaikin** [comment]
@johlj Thanks for the activity :) 

Question.. Could you clarify interested scenario?

I see these variants of examples:

Variant1: nsmgr + few different forwarders on the same node.
Variant2: nsc->nsmgr1->forwarder-{platform1}->nsmgr1->nsmgr2->forwarder-{platform2}->nsmgr2->nse?

**Comment by johlj** [comment]
Hi,

both scenarios are interesting but would say a simple scenario with:

2x forwarders
2x NSCs
2x NSEs

NSC1 connects to NSE1 with forwarder1 (and gets an interface of type A)
NSC2 connects to NSE2 with forwarder2 (and gets an interface of type B)

would be the most interesting for us at the moment.

**Comment by denis-tingaikin** [comment]
@johlj OK, added this into the Backlog issues. 
Waiting for moving this into `To do` form @edwarnicke
