### ISSUE TITLE
Re-calculate limits with k8s/vertical-pod-autoscaler 

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#5494]
Our first limits were set in https://github.com/networkservicemesh/deployments-k8s/pull/727

That was good for first step but it is not looking good for now. We still see issues with limits on different systems.

## Solution

Re-calcluate limits with https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we schedule this for v1.4.0?

**Comment by denis-tingaikin** [comment]
This looks super actual. Many users face tiny limits.

/cc @glazychev-art

**Comment by denis-tingaikin** [comment]
@edwarnicke 

We started work with this, because many customers report about tiny limits on some components

**Comment by denis-tingaikin** [comment]
Example of the work for the vertical-pot-autoscaler

![image](https://user-images.githubusercontent.com/49399980/207374135-7489f074-070a-4661-907f-e55482d4fa89.png)

**Comment by NikitaSkrynnik** [comment]
## Subtasks
- [ ] Check find request perfomance in registry-k8s ~ 3h

**Comment by NikitaSkrynnik** [comment]
Recommendations from VPA for 10, 20, 30, 40 NSCs and NSEs (Kernel2Ethernet2Kernel example, dataplane healing disabled)
![image](https://user-images.githubusercontent.com/93182827/209650363-f57a6f43-1bca-4e6e-a194-0426a0761370.png)

40 NSCs and NSEs is the maximum at which all 40 pings go normally. If we deploy 50 NSCs and NSEs some pings stop working despite the fact that all requests were successful.

@edwarnicke Should we investigate the issue with 50 NSCs and NSEs now?

Here are logs from NSM with 50 NSCs and NSEs:
[log.zip](https://github.com/networkservicemesh/deployments-k8s/files/10307468/log.zip)
