### ISSUE TITLE
Conditional routing between several network services

### ISSUE THREAD

**Issue by yuraxdrumz** [networkservicemesh/deployments-k8s#5827]
Hello.
I have a question that I did not find an answer for and I would love for an explanation.

I have a use case, where I want 1 nsc to be connected to 2 network endpoints behind 2 different network services.
I want to conditionally route to the network endpoints based on the destination address.
Let's say when dst is inside a specific internal network, like 10.x.x.x/24, I want to go to service S1, otherwise I want to default to S2.
I made up a network service definition of what I have in mind. Is something like this possible?
![conditional](https://user-images.githubusercontent.com/17418978/167854105-689a7f39-a5e0-40f1-8fe8-6d4ec57c0467.png)

Thanks!

**Comment by edwarnicke** [comment]
@yuraxdrumz 

Short answer: Yes
Long answer: Not quite the way you are thinking :)

In Network Service Mesh, and NSE can specify the [ConnectionContext](https://github.com/networkservicemesh/api/blob/a1414febd72770e0f7c75bf90ccbe58676baa0c1/pkg/api/networkservice/connectioncontext.proto#L96-L102) in the Connection it returns.  This includes an [IPContext](https://github.com/networkservicemesh/api/blob/a1414febd72770e0f7c75bf90ccbe58676baa0c1/pkg/api/networkservice/connectioncontext.proto#L59-L77) which includes, among other things:

1.  The IP addresses to assign to both ends of the vWire
2.  The *routes* to be created in the NSC that should point to that vWire

So to take your example, NSE-1 can simply return the route 10.10.3.0/24 in its ConnectionContext and NSM (presuming no conflict with excluded prefixes like the cluster prefixes) will program them into the NSC.

Your 'else dst is x.x.x.x/x'  would just be a route returned by NSE-1.

Does that make sense?

**Comment by yuraxdrumz** [comment]
@edwarnicke 
Yes, I assume you meant NSE-2 in the last sentence.

Thanks

**Comment by edwarnicke** [comment]
@yuraxdrumz Thanks for catching that typo, I've fixed it now :)
