### ISSUE TITLE
Recheck using URL in kustomize

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#6177]
### Description
We don't use URL in kustomize in the setup for some of the last tests.

For example:
[VL3 - basic](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3/basic)
[VL3 - scale from zero](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3/scale-from-zero)
[Interdomain](https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/interdomain/README.md)

Previous issue: https://github.com/networkservicemesh/deployments-k8s/issues/2672

**Comment by denis-tingaikin** [comment]
Seems like done
