### ISSUE TITLE
Wrong port to access the registry in interdomain test

### ISSUE THREAD

**Issue by sepehrjavid** [networkservicemesh/deployments-k8s#6302]
Hello,
I have been testing the FloatingKernel2Vxlan2Kernel usecase in the interdomain example and I have encountered an issue. The version of the kind used is 0.8.1 and the NSM version was 1.3.0 and all clusters are on one single VM in OpenStack. Apparently the registry proxy of cluster1 resolves the IP address of the registry in cluster2 correctly, however, uses the wrong port number to access it. Therefore fails to dial and the test also fails. The nodePort allocated to the registry in this example is 32209 which should be the port to be used in order to dial the registry in cluster2 from outside while cluster1 is using the port number 5002 which is the container port. I have also verified that the cluster2 registry is accessible using netcat with the port number 32209. Here is the reported logs from cluster1 registry and the active services in cluster2 after following the instructions for testing the mentioned usecase.

![Screenshot from 2022-05-30 14-58-42](https://user-images.githubusercontent.com/32390553/170996344-9e55194a-c81d-4df7-b962-9f54938970d0.png)

Taking a closer look, it appears that the port used to listen on and dial to are both retrieved from the value of an environment variable called REGISTRY_MEMORY_LISTEN_ON in the registry-memory.yaml file. However, these to ports may differ depending on a situation such as the one here.
Could you please help me find a solution to this?
Thanks in advance

**Comment by sepehrjavid** [comment]
Hi @denis-tingaikin 

I checked the result of the IPAM and it seems like the CLUSTER_CIDRs are not included in that. I followed the provided instructions for the loadbalancer but should I add the IPAM subnets manually?

here's a partial output of the docker network inspect command

![Screenshot from 2022-05-31 14-08-03](https://user-images.githubusercontent.com/32390553/171160302-cdcd0367-426e-4450-91b9-f34730764934.png)

**Comment by denis-tingaikin** [comment]
> I checked the result of the IPAM and it seems like the CLUSTER_CIDRs are not included in that. I followed the provided instructions for the loadbalancer but should I add the IPAM subnets manually? 

As. I can see everything is looking valid.

But this is defently requires a bit more diagnostics. 


Could you please run/attach this:
1. Attach logs from `nsc` and `nse` containers
2. `kubect describe nodes` for each cluster
3. Try to run from nsc and nse followting things: `nslookup kubernetes.default`,  `nslookup exposed-kube-dns.kube-system.my.cluster1`, `nslookup exposed-kube-dns.kube-system.my.cluster2`, `nslookup exposed-kube-dns.kube-system.my.cluster3`

**Comment by sepehrjavid** [comment]
Sorry for the delay to reply, here are the logs:

NSC shell commands:

![nsc_exec](https://user-images.githubusercontent.com/32390553/171398926-b67aad64-2776-47f2-ad79-d69366659803.png)

NSE shell commands:

![nse_exec](https://user-images.githubusercontent.com/32390553/171399055-da5569e0-002f-4ae4-ab7e-5d79bffeeff4.png)

kubectl descibe nodes for cluster 1:
[cluster1.txt](https://github.com/networkservicemesh/deployments-k8s/files/8813815/cluster1.txt)

kubectl descibe nodes for cluster 2:
[cluster2.txt](https://github.com/networkservicemesh/deployments-k8s/files/8813816/cluster2.txt)

NSC logs:
[nsc.txt](https://github.com/networkservicemesh/deployments-k8s/files/8813817/nsc.txt)

NSE logs:
[nse.txt](https://github.com/networkservicemesh/deployments-k8s/files/8813819/nse.txt)
