### ISSUE TITLE
Add Floating interdomain + autoscale + vl3 example

### ISSUE THREAD

**Issue by anastasia-malysheva** [networkservicemesh/deployments-k8s#6345]
Add example that combines 3 features: Floating interdomain, autoscale and Vl3.
Expected result is 3 clusters which are connected with VL3 network. 
Floating interdomain example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/interdomain/usecases/FloatingKernel2Vxlan2Kernel
Vl3 with scale from zero example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3-scale-from-zero
Use case:
- two nsc starts on two different clusters
- on each clusters autoscale starts.
- each nsc connects to the autoscale, to create VL3 endpoints which are registring to the floating registry and can connect to each other.

**Comment by glazychev-art** [comment]
Merged: https://github.com/networkservicemesh/deployments-k8s/pull/7057
