### ISSUE TITLE
Using PBR configuration for Internet access

### ISSUE THREAD

**Issue by BenAgai** [networkservicemesh/deployments-k8s#6488]
Hi,
I wanted to use the PBR (Policy Based Routing) feature for Internet access functionality.
I created the following topology:

<img width="690" alt="Screen Shot 2022-06-20 at 14 00 22" src="https://user-images.githubusercontent.com/28253368/174587929-47d57296-21b5-49b2-b6e2-891ae90ee4b3.png">

Where
1. The payload type is IP.
2. The NSE had the following configurations:
    a. NAT (MASQUERADE) rule configured upon boot
    b. PBR configuration file

When applying the relevant yaml files the NSC successfully connected to the NSE and all relevant routing configurations were applied on the NSC according to PBR configuration.

I then tried to ping from the NSC to 1.1.1.1 and saw the following behavior:
1. The ICMP request arrived from the NSC to the NSE and was sent out properly (the MASQUERADE rule changed the source IP as expected).
2. An ICMP reply was received by the NSE and forwarded to the relevant NSM interface
4. No ICMP reply was received by the NSC

After researching the issue, I got suspicious with the Wireguard tunnel’s allowedIPs configuration dropping the ICMP reply.
In order to validate this, I refactored the code of the VPP forwarder so that it always adds 0.0.0.0/0, ::/0 to the allowedIPs configuration.

I later deployed this version of VPP forwarder and perform the ping again - it all worked properly as expected (I also downloaded files, as part of my tests, from the internet through the NSC).

I wanted to ask you the following questions:
1. Did I misunderstood the use of PBR for Internet access?
2. Is there other way to make the above work without changing the VPP forwarder’s code?

Thanks,
Ben Agai

**Comment by glazychev-art** [comment]
Hi @BenAgai,
Could you please provide an example configuration including the MASQUERADE rules and PBR?
At first glance this seems to be a masquerade problem, if a change in the forwarder helps. Perhaps the reverse IP replacement is incorrect.
If you have any NSM or VPP logs, it would be great if you share them!

**Comment by glazychev-art** [comment]
Hi @BenAgai,
We've added 0.0.0.0/0 and ::/0 to allowedIPs by default. 
Could please you check this on the latest `main` version or on `v1.5.0-rc.1`?

**Comment by BenAgai** [comment]
Hi @glazychev-art,
Sorry for the late response.
I have verified the above scenario with v1.5.0 and it works properly :)

Thanks for the fix, very good job!
