### ISSUE TITLE
【help】why my NSC pod stuck in Init state

### ISSUE THREAD

**Issue by zhaowei413** [networkservicemesh/deployments-k8s#6680]
After I have created a NetworkService, then I create a client pod which request that network service, but the pod will always 
stucked in this state and not go on, why? Thanks!

![image](https://user-images.githubusercontent.com/69899139/178753434-dddabcf8-ebdc-42c7-a18e-b5e2232f2e43.png)

![image](https://user-images.githubusercontent.com/69899139/178753858-d82aaf83-b32c-4f78-8651-cb0c6c252635.png)

![image](https://user-images.githubusercontent.com/69899139/178754247-f837bc10-8d51-4dd4-b4af-8ce35148594c.png)

**Comment by denis-tingaikin** [comment]
Hello @zhaowei413!

This is could be related to ns/nse status.

```bash
kubectl describe netsvc -A
kubectl describe nses -A
```

Could you please attach these things?

**Comment by zhaowei413** [comment]
> Hello @zhaowei413!
> 
> This is could be related to ns/nse status.
> 
> ```shell
> kubectl describe netsvc -A
> kubectl describe nses -A
> ```
> 
> Could you please attach these things?

Thanks for reply, the log is so long so I paste in other mail

**Comment by glazychev-art** [comment]
Hi @zhaowei413 
In short, I think it's because you have 2 clients - `alpine` and `iperfmod-c`. You need to delete one of them or use a wider prefix for `nse-kernel` - `NSM_CIDR_PREFIX`

If you are using this example - https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/README.md, you may notice that NSE has env `NSM_CIDR_PREFIX: 172.16.1.100/31`. From this prefix it allocates IP addresses - for the Endpoint (nse-kernel) and the Client.
But 172.16.1.100/31 has only two addresses - 172.16.1.100 and 172.16.1.101. So, you can set something like 172.16.1.100/24 or just delete one of the client (I think you just need to delete `- client.yaml` from the kustomization file if you prefer `iperfpod-c`)

**Comment by zhaowei413** [comment]
> Hi @zhaowei413 In short, I think it's because you have 2 clients - `alpine` and `iperfmod-c`. You need to delete one of them or use a wider prefix for `nse-kernel` - `NSM_CIDR_PREFIX`
> 
> If you are using this example - https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/nse-composition/README.md, you may notice that NSE has env `NSM_CIDR_PREFIX: 172.16.1.100/31`. From this prefix it allocates IP addresses - for the Endpoint (nse-kernel) and the Client. But 172.16.1.100/31 has only two addresses - 172.16.1.100 and 172.16.1.101. So, you can set something like 172.16.1.100/24 or just delete one of the client (I think you just need to delete `- client.yaml` from the kustomization file if you prefer `iperfpod-c`)


you are right, I have successfully add other Pod to this example network of nse-composition, as picture bellow, but my final target is to created my own service function chain based on my on business Pod, so that means I should add a new container of image: "ghcr.io/networkservicemesh/cmd-nse-icmp-responder:v1.2.0" to every business Pod on this chain?  Thanks.
 



![image](https://user-images.githubusercontent.com/69899139/179401264-1c7accbb-f816-4b48-818c-9f437285990a.png)

**Comment by glazychev-art** [comment]
Okay, you can also take a look at basic examples - https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic - these use cases can be useful :)

**Comment by edwarnicke** [comment]
@zhaowei413 It may be worth talking more about your use case.  Its possible that you would be better served by a vL3 NSE with some other Pods SFCed in front of it :)

**Comment by zhaowei413** [comment]
> Okay, you can also take a look at basic examples - https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic - these use cases can be useful :)

hi， @glazychev-art   It seems I should read source code in https://github.com/networkservicemesh/sdk/tree/main/pkg and like https://github.com/networkservicemesh/cmd-nse-firewall-vpp and so on, or I do not know many usage such as "fallthrough: true" in NetworkService definition, is that so? Thanks!

**Comment by denis-tingaikin** [comment]
@zhaowei413 I think you're correct and we need to add more explanations. Could you say more about your expectations about the information that you would like to see? 

Also currently we have a two sources of NSM docs:

1. This examples repo - https://github.com/networkservicemesh/deployments-k8s
2. NSM Site - https://networkservicemesh.io/docs/concepts/enterprise_users/

Which one you'd prefet to see updated with this info?

**Comment by zhaowei413** [comment]
> @zhaowei413 I think you're correct and we need to add more explanations. Could you say more about your expectations about the information that you would like to see?
> 
> Also currently we have a two sources of NSM docs:
> 
> 1. This examples repo - https://github.com/networkservicemesh/deployments-k8s
> 2. NSM Site - https://networkservicemesh.io/docs/concepts/enterprise_users/
> 
> Which one you'd prefet to see updated with this info?

I think examples repo maybe need more info about images introduction which is used in it (cmd-nse-vl3-vpp/cmd-nse-icmp-responder/...../......)
