### ISSUE TITLE
It had better add "my-vl3-network" defenition in to example "features/vl3-basic"

### ISSUE THREAD

**Issue by zhaowei413** [networkservicemesh/deployments-k8s#6870]
In this example, NSC and NSE use the NetworkService  "my-vl3-network", but it has no defenition in it!
Example "vl3-dns" has the same issue.

**Comment by denis-tingaikin** [comment]
That is good point. 

At this moment we're using self registration via env https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/features/vl3-dns/nse-patch.yaml#L16

We'll do replace this to the netsvc defenition as you proposed. 
Thank you!

**Comment by denis-tingaikin** [comment]
Should be resolved with https://github.com/networkservicemesh/deployments-k8s/pull/6903
