### ISSUE TITLE
【help】Does NSM support  loop chain?

### ISSUE THREAD

**Issue by zhaowei413** [networkservicemesh/deployments-k8s#6952]
for example, I want the data flow to be transferred in loop, which means the NSC and NSE are the same pod, is it possible for such user case? The picture bellow is an example, the data coming in CNF1 from VF1, and after go through some business Pods, the data flow back to CNF1. How can I design such a network service, it seems NSC and NSE are the same CNF1 Pod. 

![image](https://user-images.githubusercontent.com/69899139/181303823-66f8fb68-0cfd-4e8c-b89b-63094785d643.png)

**Comment by edwarnicke** [comment]
@zhaowei413 This is in the generic supportable.  Could you describe a bit more what you are doing in the loop though?

As you are no doubt aware, when forming network loops, at least one of the elements has to be intelligent enough to determine when to *stop* looping traffic :)  I'm curious which one is doing that above?

Also, NSM is capable of fairly sophisticated topologies, it may be that if we know a bit more about the problem you are trying to solve we can suggest a more effective topology :)

**Comment by zhaowei413** [comment]
> @zhaowei413 This is in the generic supportable. Could you describe a bit more what you are doing in the loop though?
> 
> As you are no doubt aware, when forming network loops, at least one of the elements has to be intelligent enough to determine when to _stop_ looping traffic :) I'm curious which one is doing that above?
> 
> Also, NSM is capable of fairly sophisticated topologies, it may be that if we know a bit more about the problem you are trying to solve we can suggest a more effective topology :)

@edwarnicke in the loop chain, there are pods for firewall or just pass though. The data into CNF1 need to flow through these business and security APP Pods and then return to CNF1, and finally flow out of CNF1.
what we need is just the picture bellow, so how to get a more effective topology? Thanks

![image](https://user-images.githubusercontent.com/69899139/182351170-bedaf48f-7643-4df0-96f8-974f990c286d.png)

**Comment by denis-tingaikin** [comment]
I think this one could be intresting to check/implement for v1.6.0

@edwarnicke Thoughts?

**Comment by glazychev-art** [comment]
@zhaowei413 
How do you think, is a scenario without the loop possible for you?

I have concerns that there may be problems with routing if NSC and NSE are on the same pod. 
Because the interfaces for both the NSC and the NSE will be in the network namespace of the same pod...
