### ISSUE TITLE
which example is using VM as NSC or NSE?

### ISSUE THREAD

**Issue by zhaowei413** [networkservicemesh/deployments-k8s#7048]
In the NSM Concepts document, we can see that it supports using VM as NSC or NSE in the network service chain, but it seems do not to have VM-related use cases  in the given examples(https://github.com/networkservicemesh/deployments-k8s), is that I miss it? Thank you!

![image](https://user-images.githubusercontent.com/69899139/182848857-fce464f3-4051-493e-80a7-312b5e0eb84c.png)

**Comment by ZhiyongYang2020** [comment]
if there is the case that packet VM running as one element of NSM service chaining in one cluster?, e.g. CNF->VNF->CNF?

**Comment by ZhiyongYang2020** [comment]
if NSM supports kubevirt VMs as part of chaining in K8S? Do we have similar test cases?
