### ISSUE TITLE
Do we plan to run remote vlan examples on CI?

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/deployments-k8s#7056]
Examples:
1. https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Kernel2RVlanBreakout
2. https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Kernel2RVlanInternal
3. https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Kernel2RVlanMultiNS

**Comment by NikitaSkrynnik** [comment]
@ljkiraly

**Comment by ljkiraly** [comment]
@NikitaSkrynnik Yes, this is done by the PR: networkservicemesh/integration-k8s-kind/pull/584
The main suite is the networkservicemesh/deployments-k8s/tree/main/examples/remotevlan which includes the ovs and vpp cases and these cases includes the test cases above. So the mentioned 3 example runs with ovs forwarder and vpp forwarder also.

Sorry for late answer.

**Comment by NikitaSkrynnik** [comment]
@ljkiraly Thank you for your answer. I think we can close this issue.

**Comment by NikitaSkrynnik** [comment]
Closed by https://github.com/networkservicemesh/integration-k8s-kind/pull/584
