### ISSUE TITLE
Namespace annotation - duplicate values

### ISSUE THREAD

**Issue by ThetaDR** [networkservicemesh/deployments-k8s#7676]
## Expected Behavior

Pods start when NSM annotation is added to namespace

## Current Behavior

It's getting stuck on replicaset step.

## Failure Information (for bugs)

ReplicaSets have errors related to duplicate values

## Steps to Reproduce

1. Setup interdomain NSM
2. Add vl3 nse
3. Apply configuration with NSM annotation in namespace with any Deployments

## Context

* NSM Version: main branch (Wed, Oct 26th)

**Comment by denis-tingaikin** [comment]
Seems like fixed
