### ISSUE TITLE
Include MTU adjustment checks in remote VLAN examples

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/deployments-k8s#7738]
## Expected Behavior

The MTU value of the interface in NSC should not be bigger than the MTU value set on base interface

## Current Behavior

MTU is not checked currently. Some failures are slipping through the CI

## Failure Information (for bugs)

Some failures are slipping through the CI. The sub-interface now don't inherit the MTU from the host interface in vpp. That caused failure in MTU adjustment.

## Related PRs

networkservicemesh/deployments-k8s/pull/7739
networkservicemesh/sdk-vpp/pull/656
networkservicemesh/sdk-ovs/pull/203

**Comment by denis-tingaikin** [comment]
Seems like done
