### ISSUE TITLE
NSM + Consul example does not work completely

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#7896]
## Current Behavior

In the step where we create the counting pod on the first cluster, this is [done incorrectly](https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/interdomain/nsm_consul/server/counting_nsm.yaml), since we are creating a kubernetes service that resolves through coredns. 
Traffic goes through the kubernetes, not the consul.

## Failure Information (for bugs)

https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/3575942252/jobs/6013128349

**Comment by denis-tingaikin** [comment]
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4244915138/jobs/7379713610

**Comment by denis-tingaikin** [comment]
OK, seems like it was related to another issue
