### ISSUE TITLE
Some of the examples fail if they run on the same cluster second time

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#8346]
## Expected Behavior

You can run the same example many times. `Cleanup` section should free all of the acquired resources.

## Current Behavior

When I run `interdomain_Kernel2Vxlan2Kernel` example it runs without any issues the first time.
The second time the test fails because `cmd-nsc-init` container never succeeds.

## Failure Information (for bugs)

```
network service endpoint candidates not found: all forwarders have failed
```

## Steps to Reproduce

1. Create new clean cluster
2. Set up NSM
3. Run [interdomain_Kernel2Vxlan2Kernel](https://github.com/networkservicemesh/deployments-k8s/blob/db188288a3b493f26733546dbe8858f283ecc51d/examples/multicluster/usecases/interdomain_Kernel2Vxlan2Kernel/README.md)
4. Run `Cleanup` section
5. Run the same test again

## Context

* Kubernetes Version: v1.25
* NSM Version: `v1.7.0-rc.2`

## Failure Logs

Logs from ``kubectl cluster-info dump``:

[cluster-info-dump.zip](https://github.com/networkservicemesh/deployments-k8s/files/10274295/cluster-info-dump.zip)

**Comment by denis-tingaikin** [comment]
Many thanks for the issue report. We'll consider this in v1.8.0 :)

**Comment by glazychev-art** [comment]
Fixed - https://github.com/networkservicemesh/deployments-k8s/pull/8383
