### ISSUE TITLE
Sometimes vl3 network interface is recreated

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#8351]
## Expected Behavior

NSM network interface is created once and stays working until it is explicitly closed, usually when deleting the pod.

## Current Behavior

I somehow got my cluster to a state when one of the nsm interfaces was regularly deleted and recreated, making it impossible to use.

## Failure Information (for bugs)

I notices the issue when running tcpdump:

```bash
$ k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-2-nsm.pcap                 [14:12:15]
tcpdump: listening on nsm-1, link-type RAW (Raw IP), snapshot length 262144 bytes
tcpdump: pcap_loop: The interface disappeared
8 packets captured
8 packets received by filter
0 packets dropped by kernel
command terminated with exit code 1
```

I tried to capture tcpdump on istiod pod.
The interface was stable at first.
Then I deployed a second pod, with istio-proxy, that tried to connect to istiod via the nsm interface.
Right after this second pod was created nsm interface got recreated (tcp dump said "The interface disappeared", but `ip a` still showed the `nsm-1` interface in the list).
When I tried to run `tcpdump` again, I got the same error after a few seconds.
The interface became stable again after I deleted the pod with istio-proxy.

I tried this a few more times, and each time tcpdump complained about interface disappearing while istio-proxy pod existed.
Few times I even got the error that interface doesn't exist. Apparently, there is some time between interface deletion and recreation events.

## Steps to Reproduce

Unfortunately I was unable to recreate this issue.
I was experimenting with istio+nsm integration, and one time I randomly got this behavior.
But I took the `cluster-info dump` logs.

Here are rough instructions of the setup I was testing:
https://github.com/d-uzlov/deployments-k8s/blob/deployment-issue-do-not-delete/examples/interdomain/nsm_istio_vl3/clean/
There are also uncompressed `cluster-info dump` logs in this branch.

I'm not sure if these instructions will be helpful because usually they don't produce the error described in this issue.

## Context

* Kubernetes Version: v1.25
* NSM Version: `v1.7.0-rc.2`

## Failure Logs

Logs file from ``kubectl cluster-info dump``:
[dump-1.zip](https://github.com/networkservicemesh/deployments-k8s/files/10277558/dump-1.zip)

**Comment by d-uzlov** [comment]
I got this issue again.

### What I did:

I actually just refreshed my cluster, so there is not much.
I took a capture of my console command history:
```bash
 1401* ../delete-cluster.sh; ../create-cluster.sh; ../init-multicluster-2.sh
 1402  kubectl --kubeconfig=$KUBECONFIG1 apply -k ./vl3-dns\nsleep 0.5\nkubectl --kubeconfig=$KUBECONFIG1 -n ns-dns-vl3 wait --for=condition=ready --timeout=1m pod -l app=nse-vl3-vpp\nkubectl --kubeconfig=$KUBECONFIG1 -n ns-dns-vl3 wait --for=condition=ready --timeout=1m pod -l app=vl3-ipam\n
 1403  kubectl --kubeconfig=$KUBECONFIG1 apply -f istio-namespace.yaml\nistioctl install --set profile=minimal -y --kubeconfig=$KUBECONFIG1 --set meshConfig.accessLogFile=/dev/stdout\nk1 exec -n istio-system deployments/istiod -c cmd-nsc -- apk add tcpdump\n
 1404  WORK_DIR="$(git rev-parse --show-toplevel)/examples/interdomain/nsm_istio_vl3/clean/istio-vm-configs"\nVM_APP="vm-app"\nVM_NAMESPACE="vm-ns"\nSERVICE_ACCOUNT="serviceaccountvm"\nCLUSTER_NETWORK=""\nVM_NETWORK=""\nCLUSTER="Kubernetes"\n
 1405  kubectl --kubeconfig=$KUBECONFIG1 create namespace "${VM_NAMESPACE}"\nkubectl --kubeconfig=$KUBECONFIG1 create serviceaccount "${SERVICE_ACCOUNT}" -n "${VM_NAMESPACE}"\n
 1406  k1 exec -n istio-system deployments/istiod -c cmd-nsc -- ip a
 1407  time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >1-istio-standard.pcap &\nsleep 1\nk1 apply -k ubuntu-standard\nsleep 0.5\nk1 -n vl3-test wait --for=condition=ready --timeout=1m pod -l app=ubuntu\nsleep 1\nkill -2 $!\nsleep 1\nk1 delete -k ubuntu-standard\ntshark -r 1-istio-standard.pcap\n
 1408  istioctl x workload entry configure -f workloadgroup.yaml -o "${WORK_DIR}" --clusterID "${CLUSTER}" --kubeconfig=$KUBECONFIG1 --ingressIP=172.16.0.2\n# sed -i '' 's/15012/15010/' "${WORK_DIR}/mesh.yaml"\nrm -rf ubuntu-standard/istio-vm-configs\nrm -rf ubuntu-hosts/istio-vm-configs\nrm -rf ubuntu-hosts-2/istio-vm-configs\nrm -rf ubuntu-hosts-2-vmlike/istio-vm-configs\ncp -r "${WORK_DIR}" ubuntu-standard/istio-vm-configs\ncp -r "${WORK_DIR}" ubuntu-hosts/istio-vm-configs\ncp -r "${WORK_DIR}" ubuntu-hosts-2/istio-vm-configs\ncp -r "${WORK_DIR}" ubuntu-hosts-2-vmlike/istio-vm-configs\n
 1409  time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-1-nsm.pcap &\nsleep 1\nk1 apply -k ubuntu-hosts\nsleep 0.5\nk1 -n vl3-test wait --for=condition=ready --timeout=1m pod -l app=ubuntu\nk1 -n vl3-test get pod\n# k1 -n vl3-test exec deployments/ubuntu-deployment -c istio-proxy -- curl 172.16.0.2:8080/ready -vs\nsleep 1\nkill -2 $!\ntime k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-2-nsm.pcap\nsleep 1\nk1 delete -k ubuntu-hosts\ntshark -r 4-istio-tcpdump-1-nsm.pcap
 1410  k1 delete -k ubuntu-hosts
 1411  time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-1-nsm.pcap &\nsleep 1\nk1 apply -k ubuntu-hosts\nsleep 0.5\nk1 -n vl3-test wait --for=condition=ready --timeout=1m pod -l app=ubuntu\nk1 -n vl3-test get pod\nk1 -n vl3-test exec deployments/ubuntu-deployment -c istio-proxy -- curl 172.16.0.2:8080/ready -vs\nsleep 1\nkill -2 $!\n# time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-2-nsm.pcap\nsleep 1\nk1 delete -k ubuntu-hosts\ntshark -r 4-istio-tcpdump-1-nsm.pcap\n# tshark -r 4-istio-tcpdump-2-nsm.pcap\n
 1412  jobs
 1413  time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-1-nsm.pcap &\nsleep 1\nk1 apply -k ubuntu-hosts\nsleep 0.5\nk1 -n vl3-test wait --for=condition=ready --timeout=1m pod -l app=ubuntu\nk1 -n vl3-test get pod\nk1 -n vl3-test exec deployments/ubuntu-deployment -c istio-proxy -- curl 172.16.0.2:8080/ready -vs\nsleep 1\nkill -2 $!\n# time k1 exec -n istio-system deployments/istiod -c cmd-nsc -- tcpdump -i nsm-1 -U -w - >4-istio-tcpdump-2-nsm.pcap\nsleep 1\nk1 delete -k ubuntu-hosts
 1414  k1 cluster-info dump --output yaml --output-directory dump-2 --all-namespaces
 1415  cp ~/.bash_history .
 1416  cp ~/.zsh_history .
 1417  history 0
```

So, basically:
1401 — delete previous cluster, create a new one, initialize it with interdomain setup (2 clusters with metallb+dns+spire+nsm)
-- I waited some time after running this command, maybe about 0.5h
1402-1406 — deploy vl3 nse, deploy istiod client
1407 — test deployment that doesn't use nsm interface
1408 — more istio initialization
1409 — start tcpdump, deploy vl3 client with istio, wait for readiness, cleanup (kill tcpdump, delete deployment)
-- I canceled the command with ctrl+C (cleanup part didn't run)
1410 — delete deployment. I didn't stop tcpdump. Not sure if this impacted the issue.
1411 — repeat previous command
-- after command 1411 I saw some tcpdump errors from background, but I think it were different errors
-- tcp dump file was corrupted due to simultaneous writes from 2 different instances
1412 — run the same command

After 1412 I immediately saw the error from tcpdump that the interface has disappeared, and run `cluster-info dump` before doing anything else.

I'm not sure if I or someone else would be able to replicate this by running the commands as I described above. I myself haven't tried replicating this yet.
I suspect that this issue has stochastic nature, so it will be hard to reproduce reliably.
Still maybe this list of commands would be helpful.

In NSM logs I see repeated `close, request, close, request, close, request, ...`. Both istiod and test client (istio-proxy) have this pattern in cmd-nsc sidecar.

### Logs

The logs are aken right after I was the issue first time with this cluster, so they must be much cleaner than previous ones.
[dump-2.zip](https://github.com/networkservicemesh/deployments-k8s/files/10282796/dump-2.zip)

### All related information can be found here:
https://github.com/d-uzlov/deployments-k8s/tree/deployment-issue-do-not-delete-2/examples/interdomain/nsm_istio_vl3/clean

**Comment by d-uzlov** [comment]
I checked what happens if I disable NSC liveness check (I modified webhook to disable it on all clients).
It turns out the after we re-deploy a client in the second cluster this new client gets ip 172.16.0.2.
This ip was previously assigned to istiod.

I checked pings between vl3 clients.
Client in the second cluster `.0.2` can't ping anyone (except itself).
NSE `.0.1` can ping sample server `.0.3`.
Sample server `.0.3` can ping NSE `.0.1` and `.0.2` (which is probably istiod)
Istiod `.0.2` can ping sample server `.0.3` but ping to NSE `.0.1` fails.

Here are logs from both clusters in this state:
[dump-3.zip](https://github.com/networkservicemesh/deployments-k8s/files/10379901/dump-3.zip)

**Comment by d-uzlov** [comment]
> And apparently after it has restarted something went wrong.

@glazychev-art hinted me that in the current version of NSM this case isn't handled properly yet, and here's the discussion:
* https://github.com/networkservicemesh/sdk/issues/1393

**Comment by denis-tingaikin** [comment]
@edwarnicke Looks like the issue is on the vpp/govpp side. Could you have a look at the stack trace? ☝️

**Comment by denis-tingaikin** [comment]
Was fixed in https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/802
