### ISSUE TITLE
Create Interdomain version of NSE Composition example

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/deployments-k8s#8874]
## Overview

Create Interdomain version of NSE Composition example. The first half of NSEs should be on the first cluster and the second half should be on the second cluster.

## Steps
1. Deploy basic intedomain NSM setup
2. Deploy `nse-composition` service on the third cluster
3. Deploy `nse-firewall` and `nse-passthrough-1` on the first cluster
4. Deploy `nse-passthrough-2`, `nse-passthrough-3` and `nse-kernel` on the second cluster
5. Deploy `nsc-kernel` which wants `nse-composition@my.cluster3` service
6. Ping from `nsc-kernel` to `nse-kernel`

## Diagram
```mermaid
flowchart LR
nsmgr-proxy1 --> nsmgr-proxy2
subgraph cluster1
nsc --> nsmgr--> forwarder --> nse-firewall -->| ..... | passthrough-1 -->| ..... | nsmgr-proxy1[nsmgr-proxy]
    end
subgraph cluster2
    nsmgr-proxy2[nsmgr-proxy] -->| ..... | passthrough-2 -->| ..... | passthrough-3 -->| ..... | nse-kernel 
end
```

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik Could you re do diagram with https://github.com/networkservicemesh/deployments-k8s/edit/main/examples/multicluster/usecases/floating_vl3-basic/README.md?
