### ISSUE TITLE
Fix interdomain networkservice names

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#8964]
## Description 
Look at:
https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/multicluster/usecases/interdomain_Kernel2Wireguard2Kernel/cluster1/client.yaml#L9
https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/multicluster/usecases/interdomain_Kernel2Vxlan2Kernel/cluster1/client.yaml#L9

We need to rename `networkservice` names to be consistent with other examples.

**Comment by denis-tingaikin** [comment]
Also within this task, I recomment to remove refs from kustomizaiton files and use relative pathes.
