### ISSUE TITLE
`patchesStrategicMerge` field in kustomization.yaml files is deprecated

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/deployments-k8s#9036]
## Issue
`patchesStrategicMerge` field in kustomization.yaml files is deprecated now: 
https://github.com/kubernetes-sigs/kustomize/blob/release-kustomize-v5.0/api/types/kustomization.go#L64.

We should use `patches` field instead.

**Comment by glazychev-art** [comment]
We need to check that all our kubernetes clusters will work because this deprecation was only added in v5.0
