### ISSUE TITLE
Reduce tokens time from 24h to 10 minutes for each application

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#906]
## Motivation

Previously we've fixed issues with `refresh`/`timeout`:

https://github.com/networkservicemesh/sdk/pull/778
https://github.com/networkservicemesh/sdk/pull/650
https://github.com/networkservicemesh/sdk/pull/520

and now we can reduce tokens expiration for each application to 10 minutes  (it is 24h at this moment).

Also, we plan to add `refresh`/`timeout` examples, but it can be done separately:
https://github.com/orgs/networkservicemesh/projects/1#card-55928687
https://github.com/orgs/networkservicemesh/projects/1#card-55928794

**Comment by edwarnicke** [comment]
@denis-tingaikin Did this get done?  If not, why not?

**Comment by denis-tingaikin** [comment]
It is not done. It looks like we missed this ticket.

Will do. As I can see we can simply set there 10m https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/spire/server-configmap.yaml#L19

**Comment by edwarnicke** [comment]
@denis-tingaikin Token expirationTime is min(svid expirationTime, now + maxTimeout as set by env variable)... I was suggesting we fix maxTimeout's default value from 24h to 10 minutes, not that we change the Spire svid lifetime.
