### ISSUE TITLE
TestVl3_dns is not stable

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#9063]
## Incident
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4826007507/jobs/8597432798?pr=814

## Logs
[TestRunFeatureSuite.zip](https://github.com/networkservicemesh/deployments-k8s/files/11353410/TestRunFeatureSuite.zip)

**Comment by NikitaSkrynnik** [comment]
## Another Failed TestVl3_dns
### Run
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4863497938/jobs/8671287766?pr=818

### Logs
[v1.27.1.zip](https://github.com/networkservicemesh/deployments-k8s/files/11396387/v1.27.1.zip)

**Comment by glazychev-art** [comment]
Blocked by: https://github.com/networkservicemesh/sdk/issues/1457

**Comment by glazychev-art** [comment]
[TestVl3_dns_GKE.zip](https://github.com/networkservicemesh/deployments-k8s/files/11815256/TestVl3_dns_GKE.zip)

**Comment by glazychev-art** [comment]
[TestVl3_dns.zip](https://github.com/networkservicemesh/deployments-k8s/files/11916542/TestVl3_dns.zip)
https://github.com/d-uzlov/integration-k8s-kind/actions/runs/5385295197/jobs/9774156037?pr=1

**Comment by glazychev-art** [comment]
The reason is that if the Request fails on the refresh (Refresh_Requested), another unavailable forwarder (from the previous test) is selected. In this case, the connection to the current one is closed and is not re-created.

Possible solutions:
1. Increase dial timeout.
2. Do not select another forwarder until Close comes.

Blocked by: https://github.com/networkservicemesh/sdk/pull/1471
