### ISSUE TITLE
`kubectl delete` is slow in tests

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#9128]
## Expected Behavior

`kubectl delete` should delete pods instantly.

## Current Behavior

In many tests we use `alpine` container which doesn't support graceful shutdown, and makes the `delete` command hang for 30 seconds.

**Comment by d-uzlov** [comment]
By default k8s starts the main process as PID 1 which have special properties regarding signals. PID 1 in Linux is supposed to be `init` but the official `alpine` image doesn't have any such program.

One of the special properties of PID 1 is that it ignores signals. This causes the container to hang for 30 seconds before k8s forcefully kills it.

I see several solutions:
1. Use `shareProcessNamespace: true` so that containers don't use PID 1. Easy, elegant, but feels like an unsafe hack to me.
2. Modify `command` to stop on a signal. Looks ugly, but doesn't require any changes except yaml files.
  https://github.com/networkservicemesh/deployments-k8s/pull/9126
3. Use a modified container image:
  3.1. Add `init` system to alpine. For example: `tini`, `dumb-init`
  3.2. Use the modified `command` in the Dockerfile
  3.3. Use some another custom binary that can respond to signals

**Comment by denis-tingaikin** [comment]
Seems like done
