### ISSUE TITLE
Update go to v1.20.x

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/deployments-k8s#9216]
We need update go to v1.20

**Comment by edwarnicke** [comment]
Suggest updating to the most recent 1.20.x to pick up the security fixes.

**Comment by denis-tingaikin** [comment]
@LionelJouin let me know if you would like to take this one. We can help with updating repos :)

**Comment by denis-tingaikin** [comment]
@edwarnicke , @LionelJouin , @glazychev-art , @NikitaSkrynnik 

We've updated everything to go 1.20.5

Thanks!!
