### ISSUE TITLE
TestRunBasicSuite/TestMemif2Vxlan2Memif can fail on ci

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#954]
## Logs
[Container logs](https://github.com/networkservicemesh/deployments-k8s/files/6363819/logs-230.zip)

**Comment by denis-tingaikin** [comment]
[Containers logs](https://github.com/networkservicemesh/deployments-k8s/files/6400854/Containers.logs.8.zip)

**Comment by denis-tingaikin** [comment]
https://github.com/networkservicemesh/integration-k8s-kind/runs/2494060190

**Comment by denis-tingaikin** [comment]
@edwarnicke I've marked this with ASAP label and moved it into the Backlog section. Let us know if we can consider this.

**Comment by edwarnicke** [comment]
@denis-tingaikin Definitely... intermittent failures in CI are important to fix.

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/cmd-nsc-vpp/pull/118
