### ISSUE TITLE
Update local spire binary in cmd Dockerfiles to support ARM docker testing

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/deployments-k8s#9574]
## Description

We are currently using `spire-v1.2.2` inside our docker containers (mostly for docker tests):
https://github.com/networkservicemesh/cmd-nsmgr/blob/main/Dockerfile#L7-L8

Because we are adding ARM support for our cmds, we also need to update `spire` to the latest version (support has been added [in this release](https://github.com/spiffe/spire/releases/tag/v1.6.4))

**Comment by bellycat77** [comment]
The task solution will depends on response for **spire** [issue](https://github.com/spiffe/spire/issues/4346)

**Comment by denis-tingaikin** [comment]
Seems like done!
