### ISSUE TITLE
missing interface in NSE after relocation

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/deployments-k8s#9863]
## Expected Behavior

The restoration time of interfaces in NSE should be more deterministic.

## Current Behavior

When more clients are deployed with two registries some interfaces are missing on NSE after NSE relocation.
The node where the NSE pod runs was cordoned and the NSE was relocated. After NSE is restarted on another node one connection to an NSC fails to be restored. Based on logs the deleted NSE remains stored in registry/etcd.

## Failure Information (for bugs)

The restoration time varies and sometimes takes more then 150 seconds, sometimes restores promptly, or never restored. Note that two instance of registry-k8s are used. IPv6 address range is set into NSE because seemingly the issue pops up frequently with IPv6 addresses.

What is the expected NSE expiration time? How that depend on NSM_MAX_TOKEN_LIFETIME? (is the description in this PR still valid? https://github.com/networkservicemesh/sdk/pull/1404)

## Steps to Reproduce

- Create kind cluster with 4 worker

<details>
<summary>cluster-config</summary>

```
 > cat cluster-config-4worker.yaml 
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
  - role: worker
```

```
kind create cluster --config cluster-config-4worker.yaml --wait 300s
```

</details>

- Basic setup should be executed
- Start a second registry-k8s pod

```
kubectl scale --replicas=2 -n nsm-system deployment/registry-k8s
```

- The remote-nse-death test case from heal feature was modified:
<details>
<summary> NSE, NSC yamls </summary>

```
> git diff
diff --git a/examples/heal/remote-nse-death/base/kustomization.yaml b/examples/heal/remote-nse-death/base/kustomization.yaml
index 86c9b5db475..babceecab6b 100644
--- a/examples/heal/remote-nse-death/base/kustomization.yaml
+++ b/examples/heal/remote-nse-death/base/kustomization.yaml
@@ -7,4 +7,6 @@ namespace: ns-remote-nse-death
 resources:
 - netsvc.yaml
 - client.yaml
+- client1.yaml
+- client2.yaml
 - ../../../../apps/nse-kernel
diff --git a/examples/heal/remote-nse-death/nse-before-death/patch-nse.yaml b/examples/heal/remote-nse-death/nse-before-death/patch-nse.yaml
index a57dc99c9cf..90e6eff49a0 100644
--- a/examples/heal/remote-nse-death/nse-before-death/patch-nse.yaml
+++ b/examples/heal/remote-nse-death/nse-before-death/patch-nse.yaml
@@ -10,7 +10,7 @@ spec:
         - name: nse
           env:
             - name: NSM_CIDR_PREFIX
-              value: 172.16.1.100/31
+              value: 2001:db8::/110
             - name: NSM_SERVICE_NAMES
               value: "remote-nse-death"
             - name: NSM_REGISTER_SERVICE
```

```
> cat base/client1.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  labels:
    app: alpine1
  annotations:
    networkservicemesh.io: kernel://remote-nse-death/nsm-1
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]

> cat base/client2.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  labels:
    app: alpine2
  annotations:
    networkservicemesh.io: kernel://remote-nse-death/nsm-1
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
```

</details>

- Execute the steps as follows:
<details>
<summary> README.md </summary>
> cat README.md
# Remote NSE death

This example shows that NSM keeps working after the remote NSE death.

NSC and NSE are using the `kernel` mechanism to connect to its local forwarder.
Forwarders are using the `vxlan` mechanism to connect with each other.

## Requires

Make sure that you have completed steps from [basic](../../basic) or [memory](../../memory) setup.

## Run

Deploy NSC and NSE:
```bash
kubectl apply -k ./nse-before-death
```

Wait for applications ready:
```bash
kubectl wait --for=condition=ready --timeout=1m pod -l app=alpine -n ns-remote-nse-death
```
```bash
kubectl wait --for=condition=ready --timeout=1m pod -l app=alpine1 -n ns-remote-nse-death
```
```bash
kubectl wait --for=condition=ready --timeout=1m pod -l app=alpine2 -n ns-remote-nse-death
```
```bash
kubectl wait --for=condition=ready --timeout=1m pod -l app=nse-kernel -n ns-remote-nse-death
```

Find  NSE pod by label:
```bash
NSE=$(kubectl get pods -l app=nse-kernel -n ns-remote-nse-death --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
```

NSE:
```bash
LINKS=$(kubectl exec -n ns-remote-nse-death $NSE -- ip a | grep remote-nse | wc -l)
test $LINKS -eq 3
```

```bash
kubectl exec -n ns-remote-nse-death $NSE -- ip a
```

Cordon NSE node:
```bash
NSE_NODE=$(kubectl get pods -l app=nse-kernel -n ns-remote-nse-death --template '{{range .items}}{{.spec.nodeName}}{{"\n"}}{{end}}')
kubectl cordon $NSE_NODE
kubectl scale --replicas=0 -n ns-remote-nse-death deployment/nse-kernel
```

New NSE:
```bash
kubectl scale --replicas=1 -n ns-remote-nse-death deployment/nse-kernel
```

Wait for new NSE to start:
```bash
kubectl wait --for=condition=ready --timeout=2m pod -l app=nse-kernel -n ns-remote-nse-death
```

Find new NSE pod:
```bash
NSE=$(kubectl get pods -l app=nse-kernel -n ns-remote-nse-death --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
```

Check the new NSE:
```bash
kubectl exec -n ns-remote-nse-death $NSE -- ip a
LINKS=$(kubectl exec -n ns-remote-nse-death $NSE -- ip a | grep remote-nse | wc -l)
test $LINKS -eq 3
```

## Cleanup

Delete ns:
```bash
kubectl delete ns ns-remote-nse-death
```
```bash
kubectl uncordon $NSE_NODE
```

</details>

## Failure Logs
[missing-interface.zip](https://github.com/networkservicemesh/deployments-k8s/files/12660803/missing-interface.zip)

**Comment by NikitaSkrynnik** [comment]
@ljkiraly  Hi, I tried to reproduce the problem several times, but I didn't see any errors. I tested this setup on main branch. Could you please test it using main branch too?

**Comment by denis-tingaikin** [comment]
@ljkiraly Should be fixed in v1.11.0. Please let us know if it's still reproduciable.

**Comment by ljkiraly** [comment]
@denis-tingaikin Verification result is good. Thanks.

**Comment by ljkiraly** [comment]
@denis-tingaikin @NikitaSkrynnik Unfortunately with NSM v1.11.2 the problem occurred again. I was able to reproduce it also. I was using the steps described above. I attached the logs:
[test-nse-cordon.zip](https://github.com/networkservicemesh/deployments-k8s/files/13843537/test-nse-cordon.zip)

Earlier our nightly tests succeeded with previous NSM version, until now when using NSM v1.11.2.

**Comment by ljkiraly** [comment]
Hi @denis-tingaikin , @NikitaSkrynnik ,
This issue is really a corner case and not a really sever problem, just to clarify. It has middle priority just because it was meant that was fixed before.
I was able to reproduce the issue in v1.12.0-rc.1. Logs attached.
[testCordon-1_12.zip](https://github.com/networkservicemesh/deployments-k8s/files/13885723/testCordon-1_12.zip)
I will try to increase the QPS and the number of registry-k8s instances and note here the results.

**Comment by glazychev-art** [comment]
Thanks @ljkiraly ,
Could you please recheck attached logs? They are empty for me

**Comment by ljkiraly** [comment]
@glazychev-art , Compressed and updating again. Thanks for the notice.
[testCordon-1_12.zip](https://github.com/networkservicemesh/deployments-k8s/files/13886018/testCordon-1_12.zip)

**Comment by denis-tingaikin** [comment]
Seems like this one is fixed. Please feel free to reopen if it's reproducing.
