### ISSUE TITLE
Routing between 2 containers 

### ISSUE THREAD

**Issue by isZams** [networkservicemesh/deployments-k8s#9864]
## Question

How can I realize traffic routing within a pod where I have 2 containers configured to work with NSM?
In partciular I should realize routing between one container leveraging cmd-nse-icmp-responder and the other cmd-nsc

## Examples

In my case I have 3 pods for simplicity:
POD1 (NSC)
POD2 (the pod with the 2 containers mentioned above)
POD3 (NSE where I have the service requested by the client)
The situation with the interfaces is as follows:
POD1(172.16.0.1) === POD2[(172.16.0.0) (172.16.1.1)] === POD3 (172.16.1.0).
In short what I would like is that from POD1 I can reach POD3 via POD2.

For example using this command, the ping fails:
`kubectl exec pods/alpine -n ns-nse-composition -- ping -c 4 172.16.1.0`

Here there are the files that i'm using
[nse-kernel-composition.zip](https://github.com/networkservicemesh/deployments-k8s/files/12664791/nse-kernel-composition.zip)

Here there are the routes that i tried to use.
_iptables -t nat -A PREROUTING -i $INTERFACE -j DNAT --to 172.16.1.
  iptables -t nat -A POSTROUTING -o kernelint2 -j SNAT --to 172.16.1.1_

Here there are the logs of the pods
[all_logs.txt](https://github.com/networkservicemesh/deployments-k8s/files/12664875/all_logs.txt)

**Comment by glazychev-art** [comment]
If you apply the iptables rules above, when you `ping -c 4 172.16.0.0` you actually ping `172.16.1.0`
Is this not enough for your purpose?

**Comment by isZams** [comment]
Yes, and it works. I was wondering if it was possible to directly ping 172.16.1.0 and let the traffic go through the other pod in the middle. Something similar to the original example of nse-composition, where the NSC pings directly the NSE, passing through the other pods, but since in that case there are the vpp-forwarder and memif mechanisms i think this one is the best option. Do you agree @glazychev-art ?
Do you have any plans to also develop a kernel forwarder?

**Comment by glazychev-art** [comment]
@isZams 
I'm not sure, but probably you might be interested in:
https://github.com/kubeslice/cmd-forwarder-kernel/tree/master

**Comment by glazychev-art** [comment]
It will not be instead of a forwarder-vpp. You need to look at the general approach and use it in your passthrough pod.
But I'm not familiar with this project, so I'm not sure if this will work for you.

**Comment by isZams** [comment]
Ok, thanks again @glazychev-art.!
