### ISSUE TITLE
Feature: automatic nsc connect to nse registered with the NS after nsc is initialized and running

### ISSUE THREAD

**Issue by barby1138** [networkservicemesh/deployments-k8s#9889]
Hi All,

Thank you for your great work!!!

I have another question / feature request which could be useful for me and, I hope, for others.

Can  we implement subj.
Example:
I have NS-1 describes that all nsc connects to all nse.
I brought up ncc-1 and nse-1 and NS-1 so nsc-1 connected to nse-1.
after some time...
I want to bring up nse-2 which declares NS-1 in NSM_SERVICE_NAMES (part of NS-1)

I want client to automatically connect to nse-2 also.

I want to bring up / down nse dynamically to optimize cloud resource allocation / usage.

What do you think?
Thank you!!!

**Comment by barby1138** [comment]
This is related to:
**reconnect services dynamically #9767**
Because in case of NSC crash / redeploy it yes will connect to nse-2 - so brings inconsistent  behavior.
This also could be resolved same way by adding watcher on new nse registered inside NS
it will also make stateless NSC to NSE connect (no need to wait for NSE to bring up) which better matches CN / k8s design

Have a good day!!!

**Comment by barby1138** [comment]
Hi guys,
Will we proceed here?
Is my explanation clear or more details needed?
Thanks!!!

**Comment by denis-tingaikin** [comment]
Hello @barby1138 ,

For the best utilisation of resources, we have scale from zero topolgy, for example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/scale-from-zero.

Also, if setup requires dynamic changes, vl3 network might be a good choice: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3-basic

I see the idea of automatically connecting a client to a group of interested parties, but I don't see a strong use case that proves the need for this feature. Do you have something in mind?
